#+TITLE: Pensamientos del 2018

Recopilación de los pensamientos incluidos en las cartas de las
[[https://github.com/jaalonso/Lecturas_GLC#lecturas-del-a%C3%B1o-2018][Lecturas compartidas de GLC durante el año 2018]].

+ [[https://es.wikipedia.org/wiki/Albert_Einstein][Albert Einstein]] ::
  + Cada día sabemos más y entendemos menos.

+ [[https://es.wikipedia.org/wiki/Alberto_Moravia][Alberto Moravia]] ::
  + Sentido común: algo así como salud contagiosa.

+ [[https://es.wikipedia.org/wiki/Aldous_Huxley][Aldous Huxley]] ::
  + La experiencia no es lo que te sucede, sino lo que haces con lo que te sucede.

+ [[https://es.wikipedia.org/wiki/Ana%C3%AFs_Nin][Anais Nin]] ::
  + No vemos jamás las cosas tal cual son, las vemos tal cual somos.

+ [[https://bit.ly/37bBjJJ][André Gide]] ::
  + Muchas veces las palabras que tendríamos que haber dicho no se presentan ante
    nuestro espíritu hasta que ya es demasiado tarde.

+ [[https://bit.ly/3hXStz3][Antoni Gaudí]] ::
  + Para hacer las cosas bien es necesario: primero, el amor, segundo, la técnica.

+ [[https://es.wikipedia.org/wiki/Antonio_Machado][Antonio Machado]] ::
  + Despacito y buena letra, que el hacer las cosas bien, importa más que el
    hacerlas.
  + Entre hacer las cosas bien y hacerlas mal está el no hacerlas, como término
  + Es propio de hombres de cabezas medianas embestir contra todo aquello que no
  + Huid de escenarios, púlpitos, plataformas y pedestales. Nunca perdáis contacto
    con el suelo; porque sólo así tendréis una idea aproximada de vuestra estatura.

+ [[https://es.wikipedia.org/wiki/Antonio_Porchia][Antonio Porchia]] ::
  + Las dificultades también pasan como todo pasa, sin dificultad.

+ [[https://bit.ly/2ODZ0S0][Arturo Graf]] ::
  + El que en un arte ha llegado a maestro puede prescindir de las reglas.

+ [[https://es.wikipedia.org/wiki/Benjamin_Franklin][Benjamin Franklin]] ::
  + Dime y lo olvido, enséñame y lo recuerdo, involúcrame y lo aprendo.

+ [[https://bit.ly/3oRRBiL][Bernard Shaw]] ::
  + Cuando un hombre estúpido hace algo que le avergüenza, siempre dice que cumple
    con su deber.
  + Dichoso es el que tiene una profesión que coincide con su afición.
  + El hombre con dolor de muelas piensa que todos los que tienen dientes sanos
    son felices. El hombre pobre comete el mismo error con el rico.
  + El hombre razonable se adapta al mundo: el irracional persiste en intentar
    adaptar el mundo a sí mismo. Por lo tanto, todo progreso depende del hombre
    irrazonable.
  + El secreto de ser desdichado estriba en tener tiempo de pensar si se es, o
    no, feliz. La cura es la ocupación, porque ocupación significa preocupación;
    y la persona preocupada no es ni feliz ni infeliz, sino simplemente viva y
    activa, lo que es más agradable que cualquier felicidad hasta que uno se cansa
    de ella.
  + Es difícil, si no imposible, para la mayoría de la gente pensar de otra
    manera que no sea en la moda de su propia época.
  + La actividad es el único camino que lleva al conocimiento.
  + La gente siempre culpa a las circunstancias por lo que son. No creo en las
    circunstancias. Las personas que se llevan bien en este mundo son las personas
    que se levantan y buscan las circunstancias que quieren y, si no las
    encuentran, las hacen.
  + Los perros no molestan hasta que ladran y los necios hasta que hablan.
  + Los que son capaces, crean; los que no son capaces, enseñan.
  + Mi forma de bromear es decir la verdad. Es la broma más divertida del mundo.
  + Mientras tenemos un deseo, tenemos una razón de vivir. La satisfacción es la
    muerte.
  + No hagas a los demás como esperarías que te hicieran a ti. Puede que sus
    gustos no sean los mismos.
  + Si comienzas por sacrificarte por tus seres queridos, terminarás odiando a
    aquellos por quienes te has sacrificado.
  + Siempre hay peligro para aquellos que lo temen.
  + Soy tan partidario de la disciplina del silencio, que podría hablar hora
    enteras sobre ella.
  + Todo necio cree lo que le dicen sus maestros y llama a su credulidad ciencia o
    moralidad con tanta seguridad como su padre la llamaba revelación divina.

+ [[https://bit.ly/2BTf8MQ][Bertrand Russell]] ::
  + Al contrario del esquema habitual me he hecho gradualmente más rebelde a medida
    que envejezco.

+ [[https://bit.ly/2CgVtWH][Blaise Pascal]] ::
  + El hombre está dispuesto siempre a negar todo aquello que no comprende.
  + He redactado esta carta más extensa de lo usual porque carezco de tiempo para
    escribirla más breve.
  + La mayoría de los males les vienen a los hombres por no quedarse en casa.
  + Ni la contradicción es indicio de falsedad, ni la falta de contradicción es
    indicio de verdad.
  + Vale más saber alguna cosa de todo, que saberlo todo de una sola cosa.

+ [[https://en.wikipedia.org/wiki/Brian_Kernighan][Brian Kernighan]] ::
  + El control de la complejidad es la esencia de la programación informática.

+ [[https://en.wikipedia.org/wiki/Buckminster_Fuller][Buckminster Fuller]] ::
  + Cuando estoy trabajando en un problema, nunca pienso en la belleza. Sólo
    pienso en cómo resolver el problema. Pero cuando he terminado, si la solución
    no es bella, sé que está mal.

+ [[https://bit.ly/3o1l5tc][C.S. Lewis]] ::
  + Lo que ves y escuchas depende de qué tipo de persona eres y desde qué punto estás mirando.

+ [[https://es.wikipedia.org/wiki/Carl_Friedrich_Gauss][Carl Friedrich Gauss]] ::
  + El verdadero objetivo de la ciencia es el honor de la mente humana.
  + Las matemáticas son la reina de las ciencias y la teoría de los números es la
    reina de las matemáticas.
  + Los encantos de esta ciencia sublime, las matemáticas, sólo se le revelan a
    aquellos que tienen el valor de profundizar en ella.

+ Carl Gustav Jung ::
  + Eres lo que haces, no lo que dices que vas a hacer.

+ Carl Gustav Jung ::
  + Pensar es difícil. Por eso la mayoría de la gente prefiere juzgar.

+ Carl Sagan [[https://bit.ly/2ZX47lo][Carl Sagan]] ::
  + En la ciencia suele ocurrir que un científico diga: Es un buen argumento, yo
    estaba equivocado ́, cambie de opinión y desde ese momento no se vuelva a
    mencionar la antigua posición. Realmente pasa. Aunque no lo frecuentemente que
    debería ya que los científicos son humanos y el cambio es a veces doloroso. Pero
    ocurre cada día. No recuerdo la última vez que algo así pasó en política o
    religión.

+ Charles Dickens ::
  + Cada fracaso nos enseña algo que necesitamos aprender.

+ Cicerón ::
  + Si quieres aprender, enseña.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Hay que atender no sólo a lo que cada cual dice, sino a lo que siente y al
    motivo porque lo siente.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Humano es errar; pero sólo los estúpidos perseveran en el error.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + La necedad es la madre de todos los males.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Mi conciencia tiene para mí más peso que la opinión de todo el mundo.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Pensar es como vivir dos veces.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Si cerca de la biblioteca tenéis un jardín ya no os faltará de nada.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Si quieres aprender, enseña.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Si quieres ser viejo mucho tiempo, hazte viejo pronto.

+ Cicerón [[https://bit.ly/2AjTu2Y][Cicerón]] ::
  + Una cosa es saber y otra saber enseñar.

+ Clorindo Testa [[https://bit.ly/2CRi1xN][Clorindo Testa]], ::
  + Creo que para un pintor, para un arquitecto, la jubilación no existe. Uno sigue
    haciendo cosas mientras le salen. No las va a cortar así por una decisión de su
    voluntad; no va a quedarse con la mente en blanco.

+ Confucio ::
  + Escoge un trabajo que te guste, y nunca tendrás que trabajar ni un sólo día de
    tu vida.

+ Confucio ::
  + Lo que el sabio desea lo busca en sí mismo. El necio lo busca en los demás.

+ Constantino Cavafis ::
  + Tu llegada allí es tu destino. Mas no apresures nunca el viaje. Mejor que dure
    muchos años y atracar, viejo ya, en la isla, enriquecido de cuanto ganaste en el
    camino.

+ Dan Brown [[https://bit.ly/3fmrElv][Dan Brown]] ::
  + Solo hay un agente infeccioso que viaje más rápido que un virus. El miedo.

+ David Hilbert ::
  + Es un error creer que el rigor es enemigo de la sencillez. Al contrario,
    encontramos confirmado por numerosos ejemplos que el método riguroso es al
    mismo tiempo el más simple y el más fácil de comprender. El propio esfuerzo
    por el rigor nos obliga a descubrir métodos de prueba más sencillos.

+ David Hilbert ::
  + Las matemáticas no son como un juego cuyas tareas están determinadas por reglas
    estipuladas arbitrariamente. Más bien, es un sistema conceptual que posee una
    necesidad interna que solo puede ser así y de ninguna manera de otra manera.

+ David Hume [[https://bit.ly/31qnUvA][David Hume]] ::
  + La belleza de las cosas existe en el espíritu de quien las contempla.

+ Donald Knuth [[https://en.wikipedia.org/wiki/Donald_Knuth][Donald Knuth]] ::
  + Cambiemos nuestra actitud tradicional en la construcción de programas. En
    lugar de imaginar que nuestra tarea principal es indicarle a una computadora
    lo que debe hacer, concentrémonos más bien en explicarle a los seres humanos
    lo que queremos que haga una computadora.

+ Donald Knuth [[https://en.wikipedia.org/wiki/Donald_Knuth][Donald Knuth]] ::
  + La ciencia es lo que entendemos lo suficientemente bien como para explicarle
    a una computadora. El arte es todo lo demás que hacemos.

+ Donald Knuth [[https://en.wikipedia.org/wiki/Donald_Knuth][Donald Knuth]] ::
  + La programación de computadoras es un arte, porque aplica el conocimiento
    acumulado al mundo, porque requiere habilidad e ingenio, y especialmente
    porque produce objetos de belleza. Un programador que subconscientemente se ve
    a sí mismo como un artista disfrutará lo que hace y lo hará mejor.

+ Doris Lessing [[https://bit.ly/34kwQ72][Doris Lessing]] ::
  + Reconsideras tu vida conforme la vas viviendo, de la misma forma que si
    estuvieras escalando una montaña y continuamente vieras los mismos paisajes
    desde distintos puntos de vista.

+ Doris Lessing [[https://bit.ly/34kwQ72][Doris Lessing]] ::
  + Todos los movimientos políticos son así: nosotros tenemos razón, todos los
    demás están equivocados. Las personas de nuestro lado que no están de acuerdo
    con nosotros son herejes y comienzan a convertirse en enemigos. Con ello viene
    una absoluta convicción de su propia superioridad moral. Hay una simplificación
    excesiva en todo y un terror a la flexibilidad.

+ Edgar Allan Poe ::
  + El mismo acto de escribir fuerza al pensamiento a hacerse lógico.

+ Edsger W. Dijkstra [[https://en.wikipedia.org/wiki/Edsger_W._Dijkstra][Edsger W. Dijkstra]] ::
  + El arte de la programación es el arte de organizar la complejidad, de dominar
    la multitud y evitar su caos bastardo.

+ Edward Kasner [[https://en.wikipedia.org/wiki/Edward_Kasner][Edward Kasner]] y
  [[https://en.wikipedia.org/wiki/James_R._Newman][James R. Newman]] ::
  + Las matemáticas son la ciencia que utiliza palabras fáciles para las ideas
    difíciles.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Cuando la vida te de limones, haz limonada.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Cultiva solo aquellos hábitos que quisieras que dominaran tu vida.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + El conocimiento es la esencia destilada de nuestras intuiciones, corroborada
    por la experiencia.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + El mayor error que puedes cometer en la vida es temer continuamente que
    cometerás uno.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Hacer que los hombres vivan en tres mundos a la vez - pasado, presente y
    futuro - ha sido el principal daño que ha hecho la religión organizada.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + La educación académica es el acto de memorizar cosas leídas en libros, y
    cosas contadas por profesores universitarios que obtuvieron su educación
    principalmente memorizando cosas leídas en libros.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + La experiencia es el nombre que todos le dan a sus errores.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + No arrojes tus penas sobre las personas; guarda la triste historia de tu vida
    para ti. Los problemas crecen contándolos.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + No hagas nada, no digas nada y no seas nada, y nunca serás criticado.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + No te tomes la vida demasiado en serio, nunca saldrás vivo de ella.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Nunca des explicaciones: tus amigos no lo necesitan y tus enemigos no te
    creerán de ninguna manera.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Si desea un trabajo bien hecho, seleccione un hombre ocupado, el otro tipo no
    tiene tiempo.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Suministrar un pensamiento es un masaje mental; pero desarrollar un
    pensamiento propio es un logro. Pensar es un ejercicio mental, y ninguna
    facultad crece, salvo cuando se ejercita.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Todo hombre es un maldito tonto durante al menos cinco minutos al día. La
    sabiduría consiste en no exceder el límite.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Un especialista es uno que se limita a sí mismo al tipo de ignorancia que ha
    elegido.

+ Elbert Hubbard [[https://bit.ly/3bgmo0A][Elbert Hubbard]] ::
  + Un fracasado es un hombre que ha cometido un error y no es capaz de
    convertirlo en experiencia.

+ Emile Durkheim ::
  + Una mente que cuestiona todo, a menos que sea lo suficientemente fuerte como
    para soportar el peso de su ignorancia, corre el riesgo de cuestionarse a sí
    misma y quedar envuelta en dudas.

+ Epicteto ::
  + Si no tienes ganas de ser frustrado jamás en tus deseos, no desees sino aquello
    que depende de ti.

+ Epicteto [[https://bit.ly/2Blzy0E][Epicteto]] ::
  + El error del anciano es que pretende enjuiciar el hoy con el criterio del
    ayer.

+ Eric T Bell, ::
  + La abstracción, a veces lanzada como un reproche a las matemáticas, es su
    principal gloria y su título más seguro de utilidad práctica. También es la
    fuente de la belleza que puede surgir de las matemáticas.

+ Felix Klein [[https://en.wikipedia.org/wiki/Felix_Klein][Felix Klein]] ::
  + Todo el mundo sabe lo que es una curva, hasta que ha estudiado suficientes
    matemáticas para confundirse a través del incontable número de posibles
    excepciones.

+ Francis Bacon [[https://bit.ly/3h3b8rV][Francis Bacon]] ::
  + Quien no quiere pensar es un fanático; quien no puede pensar, es un idiota;
    quien no osa pensar es un cobarde.

+ Friedrich Nietzsche ::
  + Desde que me cansé de buscar he aprendido a hallar.

+ Friedrich Nietzsche ::
  + Quien se sabe profundo, se esfuerza por ser claro; quien desea parecer profundo
    a la gran masa, se esfuerza por ser oscuro.

+ G. H. Hardy [[https://en.wikipedia.org/wiki/G._H._Hardy][G. H. Hardy]] ::
  + Los patrones del matemático, como los del pintor o el poeta deben ser
    hermosos; las ideas, como los colores o las palabras deben encajar de manera
    armoniosa. La belleza es la primera prueba: no hay lugar permanente en este
    mundo para las matemáticas feas.

+ G. H. Hardy [[https://en.wikipedia.org/wiki/G._H._Hardy][G. H. Hardy]] ::
  + Un matemático, como un pintor o un poeta, es un creador de patrones. Si sus
    patrones son más permanentes que los de ellos, es porque están hechos con
    ideas.

+ G. Polya ::
  + Corremos menos peligro de equivocarnos si no perdemos de vista nuestra meta.

+ G. Polya ::
  + Debemos hacer lo que podemos si no podemos hacer lo que queremos.

+ G. Polya ::
  + El fin sugiere los medios.

+ G. Polya ::
  + El objeto de la pesca no es tirar el anzuelo sino sacar el pez.

+ G. Polya ::
  + Mire alrededor suyo cuando encuentre la primera seta: las setas como los
    descubrimientos no crecen nunca solas.

+ G. Polya ::
  + No crea nada, pero reserve sus dudas para las cosas importantes.

+ G. Polya ::
  + No piensa bien quien no piensa dos veces.

+ G. Polya ::
  + Sus cinco mejores amigos son qué, por qué, dónde, cuándo y cómo.

+ G.H. Hardy ::
  + A mathematician, like a painter or poet, is a maker of patterns. If his
    patterns are more permanent than theirs, it is because they are made with
    ideas.

+ Georg Cantor [[https://en.wikipedia.org/wiki/Georg_Cantor][Georg Cantor]] ::
  + En matemáticas, el arte de hacer preguntas es más valioso que la resolución
    de problemas.

+ Georg Cantor [[https://en.wikipedia.org/wiki/Georg_Cantor][Georg Cantor]] ::
  + La esencia de las matemáticas es su libertad.

+ George Boole [[https://en.wikipedia.org/wiki/George_Boole][George Boole]] ::
  + Por muy correcto que parezca un teorema matemático, nunca hay que conformarse
    con que no haya algo imperfecto en él hasta que también dé la impresión de ser
    bello.

+ George Lakoff [[https://bit.ly/31dDTvO][George Lakoff]] ::
  + La idea de que la gente abandonará sus creencias irracionales ante la solidez
    de la evidencia presentada ante ella es en sí misma una creencia irracional,
    no apoyada por la evidencia.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + Es mejor resolver un problema de cinco maneras diferentes, que resolver cinco
    problemas de una sola manera.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + La belleza en las matemáticas es ver la verdad sin esfuerzo.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + La elegancia de un teorema es directamente proporcional al número de ideas
    que puedes ver en él e inversamente proporcional al esfuerzo que requiere
    verlas.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + La primera regla del descubrimiento es tener inteligencia y buena suerte. La
    segunda regla del descubrimiento es sentarse y esperar hasta que se tenga una
    idea brillante.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + La resolución de problemas es una habilidad práctica como, digamos, la
    natación. Adquirimos cualquier habilidad práctica por imitación y
    práctica. Tratando de nadar, imitas lo que otras personas hacen con sus manos
    y pies para mantener sus cabezas sobre el agua, y, finalmente, aprendes a
    nadar practicando la natación. Al intentar resolver problemas, hay que
    observar e imitar lo que hacen otras personas al resolver problemas y,
    finalmente, se aprende a resolver problemas haciéndolos.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + Las matemáticas tienen dos caras: son la ciencia rigurosa de Euclides, pero
    también son algo más. La matemática presentada a la manera euclidiana aparece
    como una ciencia sistemática y deductiva; pero la matemática en ciernes
    aparece como una ciencia experimental e inductiva. Ambos aspectos son tan
    antiguos como la propia ciencia de las matemáticas.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + Para enseñar de manera efectiva, un profesor debe desarrollar un sentimiento
    por su asignatura; no puede hacer que sus alumnos sientan su vitalidad si no
    la siente él mismo. No puede compartir su entusiasmo cuando no tiene
    entusiasmo que compartir. La forma en que expone su tema puede ser tan
    importante como el tema que expone; debe sentir personalmente que es
    importante.

+ George Pólya [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + Un gran descubrimiento resuelve un gran problema, pero hay un grano de
    descubrimiento en cualquier problema.

+ Georges Clemenceau [[https://bit.ly/36i38Bk][Georges Clemenceau]] ::
  + La vida de un hombre es interesante cuando ha cometido errores; es una muestra
    de que intentó superarse.

+ Gian-Carlo Rota [[https://bit.ly/2ZnMPit][Gian-Carlo Rota]] ::
  + Un buen maestro no enseña hechos, enseña entusiasmo, apertura de mente y
    valores.

+ Gian-Carlo Rota [[https://en.wikipedia.org/wiki/Gian-Carlo_Rota][Gian-Carlo Rota]] ::
  + El avance de las matemáticas puede ser visto como un progreso de lo infinito
    a lo finito.

+ Giovanni Sartori [[https://bit.ly/3debxWY][Giovanni Sartori]] ::
  + El único modo de resolver los problemas es conociéndolos, saber que existen. El
    simplismo los cancela y, así, los agrava.

+ Goethe ::
  + Los perezosos siempre hablan de lo que piensan hacer, de lo que harán; los que
    de veras hacen algo no tienen tiempo de hablar ni de lo que hacen.

+ Gottfried Leibniz [[https://bit.ly/3jDqKDW][Gottfried Leibniz]] ::
  + Es indigno que hombres notables pierdan su tiempo como esclavos del cálculo
    cuando podrían dejar ese trabajo en manos de cualquiera si se usaran las
    máquinas.

+ Gottfried Wilhelm Leibniz [[https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz][Gottfried Wilhelm Leibniz]] ::
  + El placer que obtenemos de la música proviene de contar, pero contando
    inconscientemente. La música no es más que aritmética inconsciente.

+ Gottlob Frege [[https://en.wikipedia.org/wiki/Gottlob_Frege][Gottlob Frege]] ::
  + Todo buen matemático es al menos medio filósofo, y todo buen filósofo es al
    menos medio matemático.

+ Groucho Marx ::
  + La política es el arte de buscar problemas, encontrarlos, hacer un diagnóstico
    falso y aplicar después los remedios equivocados.

+ Groucho Marx ::
  + Todavía no sé qué me vas a preguntar, pero me opongo.

+ Gösta Mittag-Leffler ::
  + La mejor obra del matemático es el arte, un arte altamente perfecto, tan audaz
    como los más secretos sueños de la imaginación, claro y límpido. El genio
    matemático y el genio artístico se tocan mutuamente.

+ Gösta Mittag-Leffler [[https://en.wikipedia.org/wiki/G%C3%B6sta_Mittag-Leffler][Gösta Mittag-Leffler]] ::
  + La mejor obra del matemático es el arte, un arte altamente perfecto, tan
    audaz como los más secretos sueños de la imaginación, claro y límpido. El
    genio matemático y el genio artístico se tocan mutuamente.

+ Haemin Sunim [[https://bit.ly/2D9hgQt][Haemin Sunim]] ::
  + ¿Quieres sentirte joven de nuevo? Aprende algo nuevo. Ser estudiante hace que
    tu mente esté fresca y curiosa como un niño pequeño otra vez.

+ Hans Reichenbach ::
  + La esencia del conocimiento es la generalización. Que el fuego se puede
    producir frotando la madera de cierta manera es un conocimiento derivado de la
    generalización de las experiencias individuales; la afirmación significa que
    frotar la madera de esta manera siempre producirá fuego. Por lo tanto, el arte
    del descubrimiento es el arte de la correcta generalización.

+ Henri Lebesgue ::
  + La única enseñanza que un profesor puede dar, en mi opinión, es la de pensar
    delante de sus alumnos.

+ Henri Poincaré ::
  + Las matemáticas son el arte de dar el mismo nombre a cosas diferentes.

+ Henri Poincaré ::
  + Los matemáticos dan mucha importancia a la elegancia de sus métodos y a sus
    resultados. Esto no es puro diletantismo. ¿Qué es lo que en verdad nos da la
    sensación de elegancia en una solución, en una demostración? Es la armonía de
    las diversas partes, su la simetría, su feliz equilibrio; en una palabra, es
    todo lo que introduce orden, todo lo que da unidad, lo que nos permite ver con
    claridad y comprender a la vez tanto el conjunto como los detalles.

+ Henri Poincaré [[https://es.wikipedia.org/wiki/Henri_Poincar%C3%A9][Henri Poincaré]] ::
  + Las matemáticas son el arte de dar el mismo nombre a diferentes cosas.

+ Henry Brougham [[https://bit.ly/2Yv5qZI][Henry Brougham]] ::
  + Procura buscar el conocimiento en las dificultades.

+ Henry Ford ::
  + Pensar es el trabajo más difícil que existe. Quizá sea ésta la razón por la que
    haya tan pocas personas que lo practiquen.

+ Henry Moore [[https://bit.ly/3fSs4RM][Henry Moore]] ::
  + No hay jubilación para un artista; el arte es una forma de vida y como tal no
    tiene fin.

+ Herbert A. Simon ::
  + En el campo de la computación, el momento de la verdad es la ejecución de un
    programa; todo lo demás es profecía.

+ Herbert Von Karajan [[https://bit.ly/3fFBos7][Herbert Von Karajan]] ::
  + Las influencias aparecen al principio, pero llegados a un cierto punto,
    terminan.

+ Hermann Weyl ::
  + Mi trabajo siempre trató de unir lo verdadero con lo bello; pero cuando tuve
    que elegir uno u otro, generalmente elegí lo bello.

+ Hesíodo ::
  + Sé prudente. Lo mejor en todo es escoger la ocasión.

+ Horacio [[https://bit.ly/30HaPxN][Horacio]] ::
  + A los que mucho desean les falta mucho.

+ Horacio [[https://bit.ly/30HaPxN][Horacio]] ::
  + Lo que hace falta es someter a las circunstancias, no someterse a ellas.

+ Howard Eves ::
  + Existe una distinción entre lo que se puede llamar un problema y lo que puede
    considerar un ejercicio. Este último sirve para entrenar al en alguna técnica o
    procedimiento, y requiere poco o ningún original. A diferencia de un ejercicio,
    un problema, si es apropiado para nivel, debe requerir pensamiento por parte del
    estudiante. Es imposible exagerar la importancia de los problemas en las
    matemáticas. Es por medio de los problemas que las matemáticas se desarrollan y
    se levantan por sí mismas. Cada nuevo descubrimiento en matemáticas es el
    resultado de un intento de resolver algún problema.

+ Ian Stewart ::
  + A menudo, la contribución clave de la intuición es hacernos conscientes de
    los puntos débiles de un problema, los lugares donde puede ser vulnerable a un
    ataque. Una demostración matemática es como una batalla, o si prefiere una
    metáfora menos bélica, una partida de ajedrez. Una vez que se ha identificado
    un punto débil potencial, la comprensión técnica del matemático de la
    maquinaria de las matemáticas puede utilizarse para explotarlo.

+ Ian Stewart ::
  + Criticar a las matemáticas por su abstracción es perder el punto por
    completo. La abstracción es lo que hace que las matemáticas funcionen. Si te
    concentras demasiado en una aplicación demasiado limitada de una idea
    matemática, le robas al matemático sus herramientas más importantes: analogía,
    generalidad, y simplicidad.

+ Imre Lakatos [[https://bit.ly/3bJNr6w][Imre Lakatos]] ::
  + Hay una regresión infinita en las pruebas; por lo tanto, las pruebas no
    prueban. Debes darte cuenta de que probar es un juego, que se juega mientras
    lo disfrutas y que se detiene cuando te cansas.

+ Indira Gandhi [[https://bit.ly/34FxvAi][Indira Gandhi]] ::
  + Un día mi abuelo me dijo que hay dos tipos de personas: las que trabajan, y las
    que buscan el mérito. Me dijo que tratara de estar en el primer grupo: hay menos
    competencia ahí.

+ Isaac Asimov ::
  + Nunca permitas que el sentido de la moral te impida hacer lo que está bien.

+ Israel Nathan Herstein [[https://en.wikipedia.org/wiki/Israel_Nathan_Herstein][Israel Nathan Herstein]] ::
  + El valor de un problema no es tanto el de encontrar la respuesta como el de
    las ideas e intentos que obliga su resolución.

+ Italo Calvino [[https://bit.ly/2RHtRyr][Italo Calvino]] ::
  + Renunciar a las cosas es menos difícil de lo que se cree: todo estriba en
    empezar. Una vez que has logrado prescindir de algo que creías esencial,
    adviertes que puedes pasarte también sin alguna otra cosa, y luego aún sin otras
    muchas cosas.

+ Jean Dieudonné ::
  + La vida de un matemático está dominada por una insaciable curiosidad, un deseo
    que raya en la pasión por resolver los problemas que estudia.

+ Johann Kaspar Lavater ::
  + Si quieres ser sabio, aprende a interrogar razonablemente, a escuchar con
    atención, a responder serenamente y a callar cuando no tengas nada que decir.

+ John H. Newman [[https://bit.ly/3g17HS0][John H. Newman]] ::
  + En un mundo superior puede ser de otra manera, pero aquí abajo, vivir es
    cambiar y ser perfecto es haber cambiado muchas veces.

+ John Lennon ::
  + La vida es aquello que te va sucediendo mientras estás ocupado haciendo otros
    planes.

+ John Stillwell [[https://bit.ly/2WwYbPF][John Stillwell]] ::
  + Imposibilidades aparentes que son nuevas verdades [...] números
    irracionales, números imaginarios, puntos en el infinito, espacio curvo,
    ideales y varios tipos de infinito. Estas ideas parecen imposibles al
    principio porque nuestra intuición no puede comprenderlas, pero pueden ser
    capturadas con la ayuda del simbolismo matemático, que es una especie de
    extensión tecnológica de nuestros sentidos.

+ John von Neumann [[https://en.wikipedia.org/wiki/John_von_Neumann][John von Neumann]] ::
  + Si la gente no cree que las matemáticas son simples, es sólo porque no se dan
    cuenta de lo complicada que es la vida.

+ Jorge Luis Borges [[https://bit.ly/3fz4w3V][Jorge Luis Borges]] ::
  + Que otros se jacten de las páginas que han escrito; a mi me enorgullecen las
    que he leído.

+ Jorge Luis Borges [[https://bit.ly/3fz4w3V][Jorge Luis Borges]] ::
  + Uno no es lo que es por lo que escribe, sino por lo que ha leído.

+ Joseph Joubert [[https://bit.ly/2SBOsW2][Joseph Joubert]] ::
  + El motivo no existe siempre para ser alcanzado, sino para servir de punto de
    mira.

+ José Saramago [[https://bit.ly/2TmfjFv][José Saramago]] ::
  + En la comunicación directa intervienen la mirada, el olor. En una carta puede
    caer una lágrima, pero el correo electrónico no puede ir acompañado de
    emociones. Los hombres terminarán encerrados en una habitación con pantalla,
    comunicando con todo el mundo pero solos-

+ José Saramago [[https://bit.ly/2TmfjFv][José Saramago]] ::
  + Escribo para intentar comprender, y porque no tengo nada mejor que hacer.

+ José Saramago [[https://bit.ly/2TmfjFv][José Saramago]] ::
  + Las tres enfermedades del hombre actual son la incomunicación, la revolución
    tecnológica y su vida centrada en su triunfo personal.

+ José Saramago [[https://bit.ly/2TmfjFv][José Saramago]] ::
  + Lo difícil no es vivir con otras personas, es comprenderlas.

+ José Saramago [[https://bit.ly/2TmfjFv][José Saramago]] ::
  + Los únicos interesados en cambiar el mundo son los pesimistas, porque los
    optimistas están encantados con lo que hay.

+ José Saramago [[https://bit.ly/2TmfjFv][José Saramago]] ::
  + Nuestra mayor tragedia es no saber qué hacer con nuestras vidas.

+ Karl Marx ::
  + Las ideas dominantes de una época siempre fueron sólo las ideas de una clase
    dominante.

+ Karl Pearson ::
  + El verdadero objetivo del maestro debe ser impartir una apreciación del
    método y no un conocimiento de los hechos.

+ Karl Weierstrass [[https://en.wikipedia.org/wiki/Karl_Weierstrass][Karl Weierstrass]] ::
  + Un matemático que no sea también algo de poeta nunca será un matemático
    perfecto.

+ Katherine Mansfield [[https://bit.ly/3dUHggj][Katherine Mansfield]] ::
  + ¿Qué es lo que más quiero hacer? Esto es lo que no debo dejar de preguntarme
    ante las dificultades.

+ Kurt Gödel [[https://en.wikipedia.org/wiki/Kurt_G%C3%B6del][Kurt Gödel]] ::
  + El desarrollo de las matemáticas hacia una mayor precisión ha llevado, como
    es bien sabido, a la formalización de grandes partes de las mismas, de modo
    que se puede probar cualquier teorema usando nada más que unas pocas reglas
    mecánicas.

+ Lao Tse [[https://bit.ly/3lfsbdl][Lao Tse]] ::
  + El Sabio actúa sin hacer nada.

+ Laurence J. Peter ::
  + Sólo una cosa es más dolorosa que aprender de la experiencia, y es, no aprender
    de la experiencia.

+ Leopold Kronecker [[https://en.wikipedia.org/wiki/Leopold_Kronecker][Leopold Kronecker]] ::
  + Dios creó el número natural, y todo el resto es obra del hombre.


+ León Tolstói ::
  + Hay quien cruza el bosque y sólo ve leña para el fuego.

+ León Tolstói ::
  + Un hombre es como una fracción cuyo numerador corresponde a lo que él es, en
    tanto que el denominador es lo que cree ser.

+ León Trotski [[https://bit.ly/3l7SeTp][León Trotski]] ::
  + Exponer a los oprimidos la verdad sobre la situación es abrirles el camino de
    la revolución.

+ Lin Yutang [[https://bit.ly/2J7Y88F][Lin Yutang]] ::
  + La sabiduría de la vida consiste en la eliminación de lo no esencial. En
    reducir los problemas de la filosofía a unos pocos solamente: el goce del
    hogar, de la vida, de la naturaleza, de la cultura.

+ Lin Yutang [[https://es.wikipedia.org/wiki/Lin_Yutang][Lin Yutang]] ::
  + La sabiduría de la vida consiste en eliminar lo que no sea esencial.

+ Luciano Ramalho [[https://twitter.com/ramalhoorg?lang=es][Luciano Ramalho]] ::
  + Premature abstraction is as bad as premature optimization.

+ Lucien Szpiro  [[https://en.wikipedia.org/wiki/Lucien_Szpiro][Lucien Szpiro]] ::
  + La diferencia entre los matemáticos y los físicos es que después de que los
    físicos prueban un gran resultado piensan que es fantástico, pero después de
    que los matemáticos prueban un gran resultado piensan que es trivial.

+ Lucio Anneo Séneca [[https://bit.ly/3nludJ4][Lucio Anneo Séneca]] ::
  + Es propio de un alma grande menospreciar lo grandioso y preferir la
    moderación a la desmesura.

+ Ludwig van Beethoven ::
  + Nunca rompas el silencio si no es para mejorarlo.

+ Mahatma Gandhi [[https://es.wikipedia.org/wiki/Mahatma_Gandhi][Mahatma Gandhi]] ::
  + Todos los días deberíamos oír un poco de música, leer una buena poesía,
    contemplar un cuadro hermoso y si es posible, decir algunas palabras sensatas. ¬ Goethe

+ Manuel Azaña ::
  + Si los españoles hablásemos sólo de lo que sabemos, se generaría un inmenso
    silencio, que podríamos aprovechar para el estudio.

+ Marcel Proust [[https://bit.ly/38WP93b][Marcel Proust]] ::
  + A veces estamos demasiado dispuestos a creer que el presente es el único estado
    posible de las cosas.

+ Marcel Proust [[https://en.wikipedia.org/wiki/Marcel_Proust][Marcel Proust]] ::
  + El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes
    sino en tener nuevos ojos.

+ Marco Aurelio [[https://bit.ly/2LqGY3P][Marco Aurelio]] ::
  + El universo es cambio; nuestra vida es lo que hacen nuestros pensamientos.

+ Marco Aurelio [[https://bit.ly/2LqGY3P][Marco Aurelio]] ::
  + Todo lo que escuchamos es una opinión, no un hecho. Todo lo que vemos es una
    perspectiva, no la verdad.

+ Marie Curie ::
  + Dejamos de temer aquello que se ha aprendido a entender.

+ Marie Curie ::
  + Dejamos de temer aquello que se ha aprendido a entender.

+ Mark Twain ::
  + Nunca discutas con un ignorante, te hará descender a su nivel y ahí te
    vencerá por experiencia.

+ Marvin Minsky [[https://bit.ly/3iLww67][Marvin Minsky]] ::
  + La inteligencia artificial es la ciencia de hacer que las máquinas hagan cosas
    que requerirían inteligencia si las hicieran los hombres.

+ Mary Shelley [[https://bit.ly/2IgDGm4][Mary Shelley]] ::
  + Hablar con la gente constituye ahora mismo una molestia que me alegra mucho
    poder evitar. La soledad es el único agarradero que tengo, mi mejor recurso,
    mi refugio. La soledad me beneficia: me da momentos espaciosos.

+ Michel de Montaigne [[https://bit.ly/3gQRHCN][Michel de Montaigne]] ::
  + Cuando me llevan la contraria, despiertan mi atención, no mi cólera; me ofrezco
    a quien me contradice, que me instruye. La causa de la verdad debería ser la
    causa común de uno y otro.

+ Michel de Montaigne [[https://bit.ly/3gQRHCN][Michel de Montaigne]] ::
  + El signo más cierto de la sabiduría es la serenidad constante.

+ Milton Friedman [[https://bit.ly/3lcJ0F3][Milton Friedman]] ::
  + Si no puedes formular una proposición de forma clara y sin ambigüedades, no
    la comprendes.

+ Montaigne ::
  + La señal más clara de la sabiduría es el gozo constante. Ama la vida, ama la
    belleza y la salud. Su tarea propia es saber usar esos bienes de manera
    mesurada, y saberlos perder con entereza. El alma, en efecto, se ensancha a
    medida que se llena.

+ Montesquieu ::
  + Una cosa no es justa por el hecho de ser ley. Debe ser ley porque es justa.

+ Nelson Mandela [[https://bit.ly/2OKrmd7][Nelson Mandela]] ::
  + Después de escalar una montaña muy alta, descubrimos que hay muchas otras
    montañas por escalar.

+ Nicolas Malebranche [[https://bit.ly/30APxBP][Nicolas Malebranche]] ::
  + Todas las ideas tienen alguna realidad mientras estoy pensando en ellas. (...)
    Ellas iluminan el espíritu, o se le dan a conocer; algunas incluso lo asombran,
    o hacen que él las sienta, y todo ello de mil maneras distintas.

+ Oscar Wilde ::
  + Cuanto más conservadoras son las ideas, más revolucionarios los discursos.

+ Oscar Wilde ::
  + La educación es una cosa admirable, pero es bueno recordar de vez en cuando,
    que nada que valga la pena saber puede ser enseñado.

+ Pablo Picasso ::
  + Yo no busco, encuentro.

+ Paul Cohen ::
  + Para el matemático medio que simplemente quiere saber que su trabajo tiene
    una base segura, la opción más atractiva es evitar dificultades por medio del
    programa de Hilbert. Aquí uno considera las matemáticas como un juego formal y
    solo se preocupa por la cuestión de la coherencia.

+ Paul Erdős [[https://en.wikipedia.org/wiki/Paul_Erd%C5%91s][Paul Erdős]] ::
  + ¿Por qué son hermosos los números? Es como preguntar por qué es bella la
    Novena Sinfonía de Beethoven. Si no ves por qué, alguien no puede
    decírtelo. Yo sé que los números son hermosos. Si no son hermosos, nada lo
    es.

+ Paul Halmos [[https://en.wikipedia.org/wiki/Paul_Halmos][Paul Halmos]] ::
  + Las matemáticas no son una ciencia deductiva, eso es un cliché. Cuando tratas
    de probar un teorema, no te limitas a enumerar las hipótesis y luego empiezas
    a razonar. Lo que haces es prueba y error, experimentación, conjetura.

+ Pedro Calderón De La Barca ::
  + ¿Qué es la vida? Un frenesí. ¿Qué es la vida? Una ilusión, una sombra, una
    ficción; y el mayor bien es pequeño; que toda la vida es sueño, y los sueños,
    sueños son.

+ Peter Rowlett ::
  + No hay forma de garantizar de antemano lo que las matemáticas puras
    encontrarán luego su aplicación. Solo podemos dejar que el proceso de
    curiosidad y abstracción tenga lugar, dejar que los matemáticos lleven
    obsesivamente los resultados a sus extremos lógicos, dejando la relevancia muy
    atrás, y esperar a ver qué los temas resultan ser extremadamente útiles. De lo
    contrario, cuando lleguen los desafíos del futuro, no tendremos la pieza
    correcta de matemáticas aparentemente inútiles.

+ Pierre Boutroux [[https://en.wikipedia.org/wiki/Pierre_Boutroux][Pierre Boutroux]] ::
  + La lógica es invencible, porque para combatir la lógica es necesario usar la
    lógica.

+ Plutarco [[https://bit.ly/3iwPM6r][Plutarco]] ::
  + El cerebro no es un vaso por llenar, sino una lámpara por encender.

+ Proverbio Zen ::
  + Si entiendes, las cosas son así. Si no entiendes, las cosas son así.

+ Proverbio chino ::
  + Si te caes siete veces, levántate ocho.

+ Proverbio japonés ::
  + Es mejor viajar lleno de esperanza que llegar.

+ Proverbio romano ::
  + Por la ignorancia nos equivocamos, y por las equivocaciones aprendemos.

+ Proverbio suizo ::
  + Las palabras son enanos, los ejemplos son gigantes.

+ Pío Baroja ::
  + Cuando el hombre se mira mucho a sí mismo, llega a no saber cuál es su cara y
    cuál es su careta.

+ Rafael Chirbes [[https://bit.ly/2BNCfYs][Rafael Chirbes]] ::
  + A veces cargamos las cosas con una importancia que sólo existe en nuestra
    cabeza.

+ Rafael Chirbes [[https://bit.ly/2BNCfYs][Rafael Chirbes]] ::
  + Cinismo y amargura son los dos frutos que te da el árbol de la vida.

+ Rafael Chirbes [[https://bit.ly/2BNCfYs][Rafael Chirbes]] ::
  + Cuando las ideas no te dejan ver la realidad, no son ideas, son mentiras.

+ Rafael Chirbes [[https://bit.ly/2BNCfYs][Rafael Chirbes]] ::
  + La misión del hombre en el corto espacio que le toca vagabundear sobre la
    tierra es precisamente evitar el desorden, corregir el desorden.

+ Rafael Chirbes [[https://bit.ly/2BNCfYs][Rafael Chirbes]] ::
  + Si no sabes adónde vas ningún camino es bueno.

+ Rafael Chirbes [[https://bit.ly/2BNCfYs][Rafael Chirbes]] ::
  + Sólo sobreviven quienes consiguen creerse que son lo que no son.

+ Rafael Chirbes [[https://bit.ly/2BNCfYs][Rafael Chirbes]] ::
  + Todas las juventudes se parecen, es en la madurez cuando empieza la
    diferencia, nos diferenciamos en cómo resolvemos esa desazón originaria, en
    cómo abordamos el cruce de caminos que se nos presenta a la salida de la
    juventud. El tiempo que perdimos. La imposibilidad de recuperarlo. No tener
    claro si lo que hicimos fue perder o ganar.

+ Raoult Guerin de la Grasserie ::
  + El carácter es la mitad del destino.

+ Ray Bradbury [[https://bit.ly/2JlTtA7][Ray Bradbury]] ::
  + No hace falta quemar libros si el mundo empieza a llenarse de gente que no lee,
    que no aprende, que no sabe ...

+ René Descartes ::
  + El buen sentido es lo que mejor repartido está entre todo el mundo, pues cada
    cual piensa que posee buena provisión de él.

+ René Descartes ::
  + Pensad antes de obrar y no comencéis nada sin haber consultado las
    circunstancias bien a fondo.

+ Richard Courant [[https://en.wikipedia.org/wiki/Richard_Courant][Richard Courant]] ::
  + Las matemáticas como expresión de la mente humana reflejan la voluntad
    activa, la razón contemplativa y el deseo de perfección estética. Sus
    elementos básicos son la lógica y la intuición, el análisis y la construcción,
    la generalidad y la individualidad.

+ Richard Feynman [[https://bit.ly/33Oi7jg][Richard Feynman]] ::
  + Necesitamos enseñar a que la duda no sea temida, sino bienvenida y
    debatida. No hay problema en decir: 'No lo sé'.

+ Richard Hamming [[https://en.wikipedia.org/wiki/Richard_Hamming][Richard Hamming]] ::
  + El propósito de la computación es la comprensión, no los números.

+ Richard J. Trudeau ::
  + Las matemáticas puras son el mejor juego del mundo. Es más absorbente que el
    ajedrez, más arriesgado que el póquer y dura más que el Monopoly. Es
    gratis. Se puede jugar en cualquier lugar.

+ Robert Louis Stevenson [[https://bit.ly/3qtRJpl][Robert Louis Stevenson]] ::
  + Saber lo que prefieres, en lugar de decir sumisamente amén a lo que el
    mundo te dice que debieras preferir, significa que has mantenido tu alma con
    vida.

+ Ronald Laing [[https://bit.ly/3j663Qz][Ronald Laing]] ::
  + Deberíamos dedicarnos a desaprender gran parte de lo aprendido y aprender lo
    que no se nos ha enseñado.

+ Rubén Darío ::
  + No dejes apagar el entusiasmo, virtud tan valiosa como necesaria; trabaja,
    aspira, tiende siempre hacia la altura.

+ Samuel Johnson [[https://bit.ly/33lHVDe][Samuel Johnson]] ::
  + No deseo conversar con un hombre que haya escrito más de lo que ha leído.

+ San Juan de la Cruz [[https://bit.ly/3dyloX0][San Juan de la Cruz]] ::
  + Buscad leyendo y hallaréis meditando.

+ Schopenhauer ::
  + El mundo en el cual cada uno vive depende de cómo lo conciba, y se ajusta, por
    ello, a las diferencias mentales: según sea cada mente, ese mundo resultará más
    pobre, anodino y superficial, o rico, interesante y lleno de sentido.

+ Schopenhauer ::
  + The alchemists in their search for gold discovered many other things of greater
    value.

+ Sigmund Freud ::
  + Existen dos maneras de ser feliz en esta vida, una es hacerse el idiota y la
    otra serlo.

+ Sir Arthur Conan Doyle ::
  + Una vez descartado lo imposible, lo que queda, por improbable que parezca, debe
    ser la verdad.

+ Stephen Hawking [[https://bit.ly/39qMQph][Stephen Hawking]] ::
  + El desorden aumenta con el tiempo porque nosotros medimos el tiempo en el
    sentido en el que aumenta el desorden.

+ Stephen J. Gould [[https://bit.ly/30zR1eU][Stephen J. Gould]] ::
  + Nuestras formas de aprender sobre el mundo están fuertemente influenciadas
    por las ideas preconcebidas sociales y los modos de pensar sesgados que todo
    científico debe aplicar a cualquier problema. El estereotipo de un 'método
    científico' totalmente racional y objetivo, con científicos individuales como
    robots lógicos (e intercambiables), es una mitología egoísta.

+ Swami Vivekananda [[https://bit.ly/38qowDp][Swami Vivekananda]] ::
  + Cada uno es responsable de lo que le sucede y tiene el poder de decidir lo que
    quiere ser. Lo que eres hoy es el resultado de tus decisiones y elecciones en el
    pasado. Lo que seas mañana será consecuencia de tus actos de hoy.

+ Séneca ::
  + Sin estudiar enferma el alma.

+ Séneca ::
  + ¡Estudia! No para saber una cosa más, sino para saberla mejor.

+ Sócrates ::
  + Sólo hay un bien: el conocimiento. Sólo hay un mal: la ignorancia.

+ Thich Nhat Hanh [[https://bit.ly/2E7OKPL][Thich Nhat Hanh]] ::
  + La mayor parte de nuestro sufrimiento surge de nuestras ideas y conceptos. Si
    eres capaz de liberarte de estos conceptos, la ansiedad y el miedo
    desaparecerán.

+ Tocqueville ::
  + Una idea falsa, pero clara y precisa, tendrá más poder en el mundo que una idea
    verdadera y compleja.

+ Tony Hoare [[https://en.wikipedia.org/wiki/Tony_Hoare][Tony Hoare]] ::
  + En el desarrollo de la comprensión de los fenómenos complejos, la herramienta
    más poderosa de que dispone el intelecto humano es la abstracción. La
    abstracción surge del reconocimiento de las similitudes entre ciertos objetos,
    situaciones o procesos en el mundo real y de la decisión de concentrarse en
    estas similitudes e ignorar, por el momento, sus diferencias.

+ Tony Hoare [[https://en.wikipedia.org/wiki/Tony_Hoare][Tony Hoare]] ::
  + Hay dos maneras de diseñar un software. Una forma es hacerlo tan simple que
    obviamente no haya deficiencias. Y la otra forma es hacerlo tan complicado que
    no haya deficiencias obvias.

+ Tony Hoare [[https://en.wikipedia.org/wiki/Tony_Hoare][Tony Hoare]] ::
  + ¿Cuál es el núcleo central de la ciencia de la computación? ¿Qué es lo que lo
    diferencia de los otros temas con los que se relaciona? ¿Qué es lo que el hilo
    de unión que reúne estas ramas dispares en una sola disciplina? Mi respuesta a
    estas preguntas es simple - es el arte de programar un ordenador. Es el arte
    de diseñar métodos eficientes y elegantes para conseguir que un ordenador
    resuelva problemas, teóricos o prácticos,  pequeños o grandes, simples o
    complejos. Es el arte de traducir estos diseños programas correctos y
    eficientes.


+ Tácito ::
  + Todo lo que se ignora tiende a magnificarse.

+ Umberto Eco [[https://bit.ly/33ulCNA][Umberto Eco]] ::
  + Una de las primeras cosas que se han de hacer para empezar a trabajar con una
    tesis es escribir el título, la introducción y el índice final; esto es,
    precisamente las cosas que todos los autores hacen al final.

+ Viktor Frankl ::
  + Si no está en tus manos cambiar una situación que te produce dolor, siempre
    podrás escoger la actitud con la que afrontes ese sufrimiento.

+ Voltaire [[https://bit.ly/335C5Xt][Voltaire]] ::
  + Algunos están destinados a razonar erróneamente, otros a no razonar en
    absoluto, y otros a perseguir a los que razonan.

+ Voltaire [[https://bit.ly/335C5Xt][Voltaire]] ::
  + Cuanto más lee uno, más se instruye; cuanto más medita, más se halla en
    situación de afirmar que no sabe nada.

+ Voltaire [[https://bit.ly/335C5Xt][Voltaire]] ::
  + Decimos una tontería y a fuerza de repetirla acabamos creyéndola.

+ Voltaire [[https://bit.ly/335C5Xt][Voltaire]] ::
  + El arte de la medicina consiste en mantener al paciente en buen estado de
    ánimo mientras la naturaleza le va curando.

+ Voltaire [[https://bit.ly/335C5Xt][Voltaire]] ::
  + La más feliz de todas las vidas es una soledad atareada.

+ Voltaire [[https://bit.ly/335C5Xt][Voltaire]] ::
  + Los prejuicios son la razón de los tontos.

+ Wernher von Braun [[https://bit.ly/2Y60TMJ][Wernher von Braun]] ::
  + Investigación es lo que hago cuando no sé lo que estoy haciendo.

+ William Faulkner [[https://bit.ly/2Uv6UAA][William Faulkner]] ::
  + La sabiduría suprema era tener sueños bastante grandes para no perderlos de
    vista mientras se persiguen.

+ William Faulkner [[https://bit.ly/2Uv6UAA][William Faulkner]] ::
  + La sabiduría suprema es tener sueños bastante grandes para no perderlos de
    vista mientras se persiguen.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + Cuando debemos hacer una elección y no la hacemos, esto ya es una elección.


+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + El arte de ser sabio es el arte de saber qué pasar por alto.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + El camino voluntario y soberano hacia la alegría, si perdemos la alegría,
    consiste en proceder con alegría, actuar y hablar con alegría, como si esa
    alegría estuviera ya con nosotros.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + El principio más profundo del carácter humano es el anhelo de ser apreciado.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + La unión del matemático con el poeta , el fervor con la medida, la pasión con
    la corrección, este seguramente es el ideal.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + No hay mentira peor que una verdad mal entendida por los que la oyen.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + No temas a la vida. Cree que la vida es digna de ser vivida, y tu creencia
    ayudará a crear el hecho.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + Primero una nueva teoría es tachada de absurda; luego se admite que es
    cierta, pero obvia e insignificante; finalmente, se ve tan importante que sus
    adversarios afirman que ellos mismos la descubrieron.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + Un gran número de personas piensan que están pensando cuando no hacen más que
    reordenar sus prejuicios.

+ William James [[https://bit.ly/2YD7Sg2][William James]] ::
  + Una cosa es importante si alguien la cree importante.

+ William Penn [[https://bit.ly/2X1l7Gu][William Penn]] ::
  + Dejad pensar al pueblo que gobierna y se dejará gobernar.

+ William Shakespeare ::
  + Un hombre que no se alimenta de sus sueños envejece pronto.

+ William Somerset Maugham [[https://bit.ly/3itzT1w][William Somerset Maugham]] ::
  + Como todos los hombres débiles, puso un énfasis exagerado en no cambiar de
    opinión.

+ William Somerset Maugham [[https://bit.ly/3itzT1w][William Somerset Maugham]] ::
  + La vejez está lista para emprender tareas que la juventud eludió porque
    tomaría demasiado tiempo.

+ William Somerset Maugham [[https://bit.ly/3itzT1w][William Somerset Maugham]] ::
  + Si la gente sólo hablara cuando tuviera algo que decir, el ser humano perdería
    muy pronto el uso del lenguaje.

+ William Somerset Maugham [[https://bit.ly/3itzT1w][William Somerset Maugham]] ::
  + Solo avanzada ya mi vida me di cuenta de cuán fácil es decir: no lo sé.

+ William Somerset Maugham [[https://bit.ly/3itzT1w][William Somerset Maugham]] ::
  + Sólo hay una cosa de la que estoy seguro, y es que hay muy poco de lo que uno
    pueda estar seguro.

+ Yoritomo Tashi [[https://bit.ly/2YZrXh7][Yoritomo Tashi]] ::
  + El sentido común es el arte de resolver los problemas, no de plantearlos.
