#+TITLE: Pensamientos del 2019

Recopilación de los pensamientos incluidos en las cartas de las
[[https://github.com/jaalonso/Lecturas_GLC#lecturas-del-a%C3%B1o-2019][Lecturas compartidas de GLC durante el año 2019]].

+ [[https://es.wikipedia.org/wiki/Aaron_Swartz][Aaron Swartz]] ::
  + Tengan curiosidad. Lean ampliamente. Prueben cosas nuevas. Creo que mucho de
    lo que la gente llama la inteligencia se reduce a la curiosidad.

+ [[https://es.wikipedia.org/wiki/Alain][Alain]] ::
  + En definitiva, lo importante es empezar. No importa cómo, luego habrá tiempo
  + Nada es más peligroso que una idea cuando no se tiene más que una.
  + Ver es algo más que mirar. Ver consiste en advertir los detalles. Para ver bien
    una flor se ha de mirar con lupa, por dentro.

+ [[https://es.wikipedia.org/wiki/Alain_Badiou][Alain Badiou]] ::
  + Las matemáticas fueron y siguen siendo muy importantes para la filosofía,
    porque son el ejemplo tipo de un lenguaje cuya Verdad es independiente del
    poder. Lo enunciado se demuestra o no se demuestra. No hay rey o clérigo que
    valga. Es, en cierto sentido, el primer pensamiento democrático, sometido a
    examen colectivo.

+ [[https://es.wikipedia.org/wiki/Alan_Turing][Alan Turing]] ::
  + Los programas son rompecabezas. Un juego, como cualquier otro juego.
  + Para que el hombre que hace la comprobación no tenga una tarea demasiado
    difícil, el programador debe hacer una serie de afirmaciones definidas que
    puedan ser comprobadas individualmente, y de las que se desprenda fácilmente
    la corrección de todo el programa.
  + Las máquinas me sorprenden con mucha frecuencia.

+ [[https://es.wikipedia.org/wiki/Albert_Camus][Albert Camus]] ::
  + Todas las desgracias de los hombres provienen de no hablar claro.

+ [[https://es.wikipedia.org/wiki/Albert_Einstein][Albert Einstein]] ::
  + La monotonía y la soledad de una vida tranquila estimula la mente creativa.
  + Una teoría es más impresionante cuanto mayor es la simplicidad de sus
    premisas, más diferentes tipos de cosas se relacionan y más amplia es su área
    de aplicación.

+ [[https://es.wikipedia.org/wiki/Alfred_Korzybski][Alfred Korzybski]] ::
  + Los logros del hombre descansan sobre el uso de símbolos. Nos gobiernan los
    símbolos.

+ [[https://es.wikipedia.org/wiki/Alfred_North_Whitehead][Alfred North Whitehead]] ::
  + Desde los primeros pasos de su educación el niño debe experimentar el placer
    del descubrimiento.
  + El objetivo de la ciencia es buscar explicaciones sencillas para hechos
    complejos.
  + Se requiere una mente muy inusual para llevar a cabo el análisis de lo obvio.

+ [[https://es.wikipedia.org/wiki/Andr%C3%A9_Weil][André Weil]] ::
  + El matemático seguirá su camino en la seguridad de que podrá saciar su sed en
    las mismas fuentes del conocimiento, convencido de que éstas no cesarán de
    fluir, puras y abundantes, mientras que los demás habrán de recurrir a las aguas
    cenagosas de una sórdida realidad. Si se le reprochase al matemático la soberbia
    de su actitud, si se le reclamase su colaboración, si se le demandase porqué se
    recluye en los altos glaciares a los que nadie salvo los de su clase le puede
    seguir, él contestaría, con Jacobi: *Por el honor del espíritu humano*.
  + El rigor es para el matemático lo que la moral es para el hombre. No consiste
    en probar todo, sino en mantener una distinción clara entre lo que se supone y
    lo que se prueba, y en tratar de asumir lo menos posible en cada etapa.
  + En el futuro, como en el pasado, las grandes ideas [de las matemáticas] deben
    ser ideas simplificadoras, el creador debe ser siempre el que aclare, para sí
    mismo y para los demás, los temas más complicados de las fórmulas y los
    conceptos.
  + Nada es más fructífero -todos los matemáticos lo saben- que esas oscuras
    analogías, esos reflejos inquietantes de una teoría sobre otra; esas caricias
    furtivas, esas discordias inexplicables; nada da también más placer al
    investigador. Llega el día en que esta ilusión se disuelve: el presentimiento
    se convierte en certeza; las teorías unidas revelan su fuente común antes de
    desaparecer.

+ [[https://es.wikipedia.org/wiki/Antoine_Lavoisier][Antoine Lavoisier]] ::
  + Pensamos solo por medio de las palabras. Los idiomas son verdaderos métodos
    analíticos. El álgebra, que se adapta a su propósito en cada especie de
    expresión, de la manera más simple, más exacta y mejor posible, es al mismo
    tiempo un idioma y un método analítico. El arte del razonamiento no es más que
    un lenguaje bien organizado.

+ [[https://es.wikipedia.org/wiki/Antonio_Escohotado][Antonio Escohotado]] ::
  + Mi vida ha sido feliz porque he perseguido siempre el conocimiento, en el
    sentido de cambiar de idea. Solo aprender nos permite cambiar de idea.

+ [[https://es.wikipedia.org/wiki/Antonio_Gramsci][Antonio Gramsci]] ::
  + Quiero que cada mañana sea para mi año nuevo. Cada día quiero echar
    cuentas conmigo mismo, y renovarme cada día.

+ [[https://es.wikipedia.org/wiki/Antoni_Gaud%C3%AD][Antoni Gaudí]] ::
  + La originalidad consiste en volver al origen; así pues, original es aquello que
    vuelve a la simplicidad de las primeras soluciones.

+ [[https://es.wikipedia.org/wiki/Antonio_Machado][Antonio Machado]] ::
  + Aprendió tantas cosas, que no tuvo tiempo para pensar en ninguna de
    ellas.
  + Ayudadme a comprender lo que os digo, y os lo explicaré más despacio.
  + De cada diez novedades que pretenden descubrirnos, nueve son
    tonterías. La décima y última, que no es necedad, resulta a última
    hora que tampoco es nueva.
  + El escepticismo es una posición vital, no lógica, que ni afirma ni niega, se
    limita a preguntar, y no se asusta de las contradicciones.
  + Hay que tener los ojos muy abiertos para ver las cosas como son; aún más
    abiertos para verlas otras de lo que son; más abiertos todavía para verlas
    mejores de lo que son.
  + Las razones no se transmiten, se engendran, por cooperación, en el diálogo.
  + Lo corriente en el hombre es la tendencia a creer verdadero cuanto le reporta
    alguna utilidad. Por eso hay tantos hombres capaces de comulgar con ruedas de
    molino.
  + Porque toda visión requiere distancia, no hay manera de ver las cosas
    sin salirse de ellas.
  + Sed hombres de mal gusto. Yo os aconsejo el mal gusto para combatir
    los excesos de la moda.
  + Y nadie pregunta ni nadie contesta, todos hablan solos.

+ [[https://es.wikipedia.org/wiki/Antonio_Porchia][Antonio Porchia]] ::
  + Las dificultades también pasan como todo pasa, sin dificultad.

+ [[https://es.wikipedia.org/wiki/Arist%C3%B3teles][Aristóteles]] ::
  + El ignorante afirma, el sabio duda y reflexiona.
  + Mercaderes e industriales no deben ser admitidos a la ciudanía, porque su
    género de vida es abyecto y contrario a la virtud.

+ [[https://es.wikipedia.org/wiki/Arthur_C._Clarke][Arthur C. Clarke]] ::
  + Cualquier tecnología suficientemente avanzada es indistinguible de la magia.

+ [[https://es.wikipedia.org/wiki/Baruch_Spinoza][Baruch Spinoza]] ::
  + El hombre libre, el hombre de ánimo fuerte, no odia a nadie, no se irrita con
    nadie, a nadie envidia, contra nadie se indigna, no siente desprecio por nadie y
    no experimenta la menor soberbia.
  + La actividad más importante que un ser humano puede lograr es aprender para
    entender, porque entender es ser libre.

+ [[https://es.wikipedia.org/wiki/Benjamin_Franklin][Benjamin Franklin]] ::
  + La llave que se usa constantemente reluce como plata: no usándola se llena de
    herrumbre. Lo mismo pasa con el entendimiento.
  + Los hombres son criaturas muy raras: la mitad censura lo que practica; la otra
    mitad practica lo que censura; el resto siempre dice y hace lo que debe.

+ [[https://es.wikipedia.org/wiki/Bernard_Le_Bovier_de_Fontenelle][Bernard Le Bovier de Fontenelle]] ::
  + Solemos llamar inútiles a las cosas que no comprendemos.

+ [[https://es.wikipedia.org/wiki/Bertrand_Russell][Bertrand Russell]] ::
  + Aunque esto pueda parecer una paradoja, toda la ciencia exacta está dominada
    por la idea de aproximación. Cuando un hombre te dice que sabe la verdad
    exacta sobre cualquier cosa, puedes deducir que es un hombre inexacto.
  + Cuando se quiere enseñar a los niños a pensar, se empieza por tratarlos
    seriamente cuando son pequeños, darles responsabilidades, hablarles con
    franqueza, darles privacidad y soledad, y hacerlos lectores y pensadores de
    pensamientos significativos desde el principio. Eso es si quieres enseñarles a
    pensar.
  + El mayor desafío para cualquier pensador es plantear el problema de una
    manera que permita una solución.
  + El verdadero espíritu del deleite, la exaltación que es la piedra de toque
    de la más alta excelencia, se encuentra en las matemáticas tanto como en la
    poesía.
  + La ciencia es lo que sabes, la filosofía es lo que no sabes.
  + La matemática, correctamente vista, posee no sólo la verdad, sino la belleza
    suprema - una belleza fría y austera, como la de la escultura, sin apelar a
    ninguna parte de nuestra naturaleza más débil, sin los hermosos adornos de la
    pintura o la música, pero sublimemente pura, y capaz de una perfección severa
    como sólo el arte más grande puede mostrar.

+ [[https://es.wikipedia.org/wiki/Blaise_Pascal][Blaise Pascal]] ::
  + El hombre está dispuesto siempre a negar todo aquello que no comprende.
  + La contradicción no es un signo de falsedad, ni la falta de contradicción un
    signo de verdad.
  + Toda la miseria de los hombres proviene de una única cosa, que es no saber
    permanecer en reposo en una habitación.
  + Vale más saber alguna cosa de todo, que saberlo todo de una sola cosa.

+ [[https://es.wikipedia.org/wiki/Burrhus_Frederic_Skinner][Burrhus Frederic Skinner]] ::
  + El auténtico problema no es si las máquinas piensan, sino si lo hacen los
    hombres.

+ [[https://es.wikipedia.org/wiki/Carl_Benjamin_Boyer][Carl B. Boyer]] y [[https://en.wikipedia.org/wiki/Uta_Merzbach][Uta C. Merzbach]] ::
  + Una de las lecciones que la historia de las matemáticas nos enseña claramente
    es que la búsqueda de soluciones a problemas no resueltos, ya sean
    solucionables o no, conduce invariablemente a importantes descubrimientos en
    el camino.

+ [[https://es.wikipedia.org/wiki/Carl_Friedrich_Gauss][Carl Friedrich Gauss]] ::
  + Los encantos de esta ciencia sublime, las matemáticas, sólo se le revelan a
    aquellos que tienen el valor de profundizar en ella.
  + No es el conocimiento, sino el acto de aprendizaje, y no la posesión, sino el
    acto de llegar allí, que concede el mayor disfrute.
  + Sabe que escribo lentamente. Esto se debe sobre todo a que no quedo satisfecho
    hasta que no consigo decir todo cuanto me sea posible en unas pocas palabras, y
    escribir de modo conciso lleva mucho más tiempo que hacerlo en extensión.

+ [[https://es.wikipedia.org/wiki/Carl_Gustav_Jung][Carl Gustav Jung]] ::
  + La soledad no llega por no tener personas a tu alrededor, sino por no poder
    comunicar las cosas que te parecen importantes a ti.
  + Queremos tener certezas y no tener dudas - resultados y no experimentos - sin
    ver que las certezas sólo pueden surgir a través de la duda y los resultados
    sólo a través del experimento.

+ [[https://es.wikipedia.org/wiki/Carl_Gustav_Jakob_Jacobi][Carl Gustav Jakob Jacobi]] ::
  + M Fourier opinaba que la finalidad primordial de las matemáticas consistía
    en su utilidad pública y en la explicación de los fenómenos naturales; pero un
    filósofo como él debería haber sabido que la finalidad única de la ciencia es la
    de rendir honor al espíritu humano y que por ello una cuestión sobre números
    vale tanto como una cuestión sobre el sistema del mundo.
  + Siempre se debe generalizar.

+ [[https://es.wikipedia.org/wiki/Claudio_Ptolomeo][Claudio Ptolomeo]] ::
  + Consideramos que es un buen principio para explicar los fenómenos la hipótesis
    más simple posible.
  + Todo lo que es difícil de alcanzar es atacado fácilmente por la generalidad de
    los hombres.

+ [[https://es.wikipedia.org/wiki/Confucio][Confucio]] ::
  + Exígete mucho a ti mismo y espera poco de los demás. Así te ahorrarás
    disgustos.
  + ¿Me preguntas por qué compro arroz y flores? Compro arroz para vivir y flores
    para tener algo por lo que vivir.

+ [[https://es.wikipedia.org/wiki/Daniel_Kahneman][Daniel Kahneman]] ::
  + A menudo nuestro cerebro racionaliza los pensamientos automáticos y los
    presenta como el fruto de un razonamiento elaborado. Pero son historias que nos
    inventamos para justificar decisiones que en realidad son fruto de nuestros
    prejuicios. Es una forma de engañarnos.

+ [[https://es.wikipedia.org/wiki/David_Hilbert][David Hilbert]] ::
  + Es un error creer que el rigor es enemigo de la simplicidad. Por el contrario,
    numerosos ejemplos confirman que el método riguroso es al mismo tiempo el más
    simple y el más fácil de comprender. El mismo esfuerzo por el rigor nos obliga a
    encontrar métodos de prueba más sencillos.
  + Las matemáticas son un juego que se juega de acuerdo a ciertas reglas simples
    con marcas sin sentido en el papel.
  + Un problema matemático debería ser difícil para seducirnos, pero no
    completamente inaccesible, para que no se burle de nuestros esfuerzos. Debería
    ser para nosotros una guía en el laberíntico camino hacia las verdades ocultas
    y, en última instancia, un recordatorio de nuestro placer en la solución
    exitosa.
  + Una teoría matemática no debe considerarse completa hasta que la hayas dejado
    tan clara que puedas explicársela al primer hombre con el que te encuentres en
    la calle.

+ [[https://es.wikipedia.org/wiki/David_Hume][David Hume]] ::
  + Cada solución da pie a una nueva pregunta.

+ [[https://es.wikipedia.org/wiki/Denis_Diderot][Denis Diderot]] ::
  + Cuidado con el hombre que habla de poner las cosas en orden. Poner las
    cosas en orden siempre significa poner las cosas bajo su control.
  + Las frases concisas son como clavos afilados que clavan la verdad en nuestra
    memoria.
  + Una idiotez común es creer que el que tiene más clientes es el más
    hábil.

+ [[https://es.wikipedia.org/wiki/Di%C3%B3genes_de_Sinope][Diógenes de Sínope]] ::
  + Callando es como se aprende a oír; escuchando es como se aprende a hablar; y
    después, hablando, se aprende a callar.

+ [[https://es.wikipedia.org/wiki/Donald_Knuth][Donald Knuth]] ::
  + El proceso de preparación de programas para una computadora digital es
    especialmente atractivo, no solo porque puede ser gratificante económica y
    científicamente, sino también porque puede ser una experiencia estética muy
    parecida a la composición de poesía o música.
  + El verdadero problema es que los programadores han pasado demasiado tiempo
    preocupándose por la eficiencia en los lugares equivocados y en los momentos
    equivocados; la optimización prematura es la raíz de todo mal (o al menos la
    mayor parte) en la programación.
  + Hemos visto que la programación de computadoras es un arte, porque aplica el
    conocimiento acumulado al mundo, porque requiere habilidad e ingenio, y
    especialmente porque produce objetos de belleza. Un programador que se vea
    inconscientemente como un artista disfrutará de lo que hace y lo haremos
    mejor.
  + La diferencia entre el arte y la ciencia es que la ciencia es lo que la gente
    entiende lo suficientemente bien como para explicarle a una computadora. Todo
    lo demás es arte.
  + La mejor teoría está inspirada en la práctica. La mejor práctica está
    inspirada en la teoría.

+ [[https://es.wikipedia.org/wiki/Edsger_Dijkstra][Edsger Dijkstra]] ::
  + Es imposible afinar un lápiz con una cuchilla desafilada. Es igualmente inútil
    tratar de hacerlo con diez.

+ [[https://es.wikipedia.org/wiki/Elbert_Hubbard][Elbert Hubbard]] ::
  + Las inteligencias poco capaces se interesan en lo extraordinario; las
    inteligencias poderosas en las cosas ordinarias.

+ [[https://es.wikipedia.org/wiki/%C3%89lie_Cartan][Elie Cartan]] ::
  + Más que ninguna otra ciencia, las matemáticas se desarrollan a través de una
    secuencia de abstracciones sucesivas. El deseo de evitar errores obliga a
    los matemáticos a encontrar y aislar la esencia de los problemas y las
    entidades consideradas. Llevado al extremo, este procedimiento justifica la
    conocida broma de que un matemático es un científico que no sabe lo que dice
    ni si existe o no lo que dice.

+ [[https://es.wikipedia.org/wiki/Emmy_Noether][Emmy Noether]] ::
  + Si pudiéramos ser educados dejando al margen lo que la gente piense o deje de
    pensar, y teniendo en cuenta solo lo que en principio es bueno o malo, ¡qué
    diferente sería todo!

+ [[https://es.wikipedia.org/wiki/Epicteto][Epicteto]] ::
  + No nos perturban las cosas sino las opiniones que de ellas tenemos.

+ [[https://es.wikipedia.org/wiki/Eric_Temple_Bell][Eric Temple Bell]] ::
  + "Obvio" es la palabra más peligrosa en matemáticas.
  + Uno de los aspectos más atractivos de las matemáticas es que sus paradojas
    más complejas se convierten en hermosas teorías.

+ [[https://es.wikipedia.org/wiki/Errico_Malatesta][Errico Malatesta]] ::
  + A los anarquistas les compete la especial misión de ser custodios celosos de la
    libertad, contra los aspirantes al poder y contra la posible tiranía de las
    mayorías.

+ [[https://es.wikipedia.org/wiki/Eug%C3%A8ne_Ionesco][Eugène Ionesco]] ::
  + No es la respuesta lo que nos ilumina, sino la pregunta.

+ [[https://es.wikipedia.org/wiki/Francis_Bacon][Francis Bacon]] ::
  + El hombre prefiere creer lo que prefiere que sea verdad.
  + Los primeros y más antiguos investigadores de la verdad solían arrojar su
    conocimiento en aforismos, o en frases cortas, dispersas y no metódicas.
  + Quien no quiere pensar es un fanático; quien no puede pensar es un idiota;
    quien no osa pensar es un cobarde.

+ [[https://en.wikipedia.org/wiki/G._H._Hardy][G. H. Hardy]] ::
  + Los jóvenes deben probar los teoremas, los viejos deben escribir libros.

+ [[https://es.wikipedia.org/wiki/Galileo_Galilei][Galileo Galilei]] ::
  + Nunca me he encontrado con alguien tan ignorante de quien no pudiese aprender
    algo.
  + Todas las verdades son fáciles de entender, una vez descubiertas. El
    caso es descubrirlas.

+ [[https://en.wikipedia.org/wiki/Gian-Carlo_Rota][Gian-Carlo Rota]] ::
  + El ejemplo más común de belleza en matemáticas es un paso brillante en una
    prueba que de otra manera no sería distinguida. Un teorema hermoso puede no
    ser bendecido con una prueba igualmente hermosa; con frecuencia aparecen
    teoremas hermosos con pruebas feas. Cuando a un teorema hermoso le falta una
    prueba hermosa, los matemáticos intentan proporcionar nuevas pruebas que
    coincidan con la belleza del teorema, con éxito variable. Sin embargo, es
    imposible encontrar pruebas hermosas de teoremas que no sean
    hermosos.
  + La lógica matemática no trata de la verdad, sino del juego de la verdad.

+ [[https://en.wikipedia.org/wiki/Georg_Gottlob][Georg Gottlob]] ::
  + La ciencia de la computación es la continuación de la lógica por otros
    medios.

+ [[https://es.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]] ::
  + El necio ve el principio, el sabio el final.
  + El sabio empieza por el final, el necio termina en el principio.
  + Es mucho mejor resolver un problema de cinco maneras diferentes, que resolver
    cinco problemas de una sola manera.
  + Hay que conjeturar el teorema matemático antes de probarlo: hay que planificar
    la idea de la prueba antes de completar los detalles. Hay que combinar las
    observaciones y seguir analogías: hay que intentarlo y volverlo a intentar. El
    resultado del trabajo creativo del matemático es el razonamiento demostrativo,
    una prueba; pero la prueba es descubierta por el razonamiento plausible, por la
    suposición.
  + La elegancia de un teorema matemático es directamente proporcional al número
    de ideas independientes que se pueden ver en el teorema e inversamente
    proporcional al esfuerzo que se requiere para verlas.
  + Las matemáticas consisten en contenido y conocimiento. ¿Qué es el conocimiento
    en matemáticas? La capacidad de resolver problemas.
  + Quien mal comprende, mal responde.
  + Resolver problemas es una habilidad práctica como, digamos, nadar. Adquirimos
    cualquier habilidad práctica por imitación y práctica.
  + Resolver problemas se puede considerar como la actividad humana más
    característica.
  + Según el viento, la vela. Según la tela, el traje.
  + Si el fin perseguido no está claro en nuestra mente, perderemos fácilmente
    el camino y abandonaremos el problema.
  + Un gran descubrimiento resuelve un gran problema pero hay un grano de
    descubrimiento en la solución de cualquier problema. Su problema puede ser
    modesto; pero si desafía su curiosidad y pone en juego sus facultades
    inventivas, y si lo resuelve por sus propios medios, puede experimentar la
    tensión y disfrutar del triunfo del descubrimiento.

+ [[https://es.wikipedia.org/wiki/Gottfried_Leibniz][Gottfried Leibniz]] ::
  + Dos cosas son idénticas si una puede ser sustituida por la otra sin afectar
    la verdad.
  + En el ámbito del espíritu, busca la claridad; en el mundo material, busca la
    utilidad.
  + Incluso en los juegos de niños hay cosas para interesar al matemático más
    grande.
  + La música es el placer que experimenta la mente humana al contar sin darse
    cuenta de que está contando.

+ [[https://es.wikipedia.org/wiki/Gottlob_Frege][Gottlob Frege]] ::
  + El objetivo de la prueba es, de hecho, no sólo poner la verdad de una
    proposición más allá de toda duda, sino también darnos una idea de la
    dependencia de una verdad con respecto a otra. Después de habernos convencido
    de que una roca es inamovible, al intentar moverla sin éxito, queda la siguiente
    pregunta, ¿qué es lo que lo sostiene de forma tan segura?
  + Realmente vale la pena inventar un nuevo símbolo si podemos eliminar no pocas
    dificultades lógicas y asegurar el rigor de las pruebas. Pero muchos
    matemáticos parecen tener tan poca sensación de pureza lógica y precisión que
    usarán una palabra que significa tres o cuatro cosas diferentes, antes de
    tomar la terrible decisión de inventar una nueva palabra.

+ [[https://es.wikipedia.org/wiki/Gregory_Chaitin][Gregory Chaitin]] ::
  + En cierto modo, las matemáticas no son el arte de responder preguntas
    matemáticas, es el arte de hacer las preguntas correctas, las preguntas que te
    dan una idea, las que te guían en direcciones interesantes, las que se
    conectan con muchas otras preguntas interesantes, las que tienen hermosas
    respuestas.

+ [[https://es.wikipedia.org/wiki/Haemin_Sunim][Haemin Sunim]] ::
  + Si no cambiamos por nosotros mismos, entonces el mundo nos obligará a
    cambiar, lo cual es más doloroso. El cambio es necesario para nuestro
    crecimiento espiritual.
  + Si quiero convencer a alguien, primero escucho con atención. Incluso si
    tengo razón, no se convencerá hasta que se sienta escuchado y respetado.

+ [[https://es.wikipedia.org/wiki/Hecato_de_Rodas][Hecato de Rodas]] ::
  + Si dejas de esperar, dejarás de temer.

+ [[https://es.wikipedia.org/wiki/Henri_Bergson][Henri Bergson]] ::
  + Lo que hacemos depende de lo que somos; pero debe añadirse que somos, en
    cierta medida, lo que hacemos y que nos creamos continuamente a nosotros
    mismos.

+ [[https://es.wikipedia.org/wiki/Henri_Poincar%C3%A9][Henri Poincaré]] ::
  + El sentimiento de la belleza matemática, de la armonía de los números y de
    las formas, de la elegancia geométrica. Es un sentimiento genuinamente
    estético, que todos los matemáticos conocen. Y esto es sensibilidad.
  + El verdadero método para prever el futuro de las matemáticas es estudiar su
    historia y su estado actual.
  + La ciencia son hechos; de la misma manera que las casas están hechas de
    piedras, la ciencia está hecha de hechos; pero un montón de piedras no es una
    casa y una colección de hechos no es necesariamente ciencia.
  + Los matemáticos conceden gran importancia a la elegancia de sus métodos y sus
    resultados. Esto no es puro diletantismo. ¿Qué es lo que nos da la sensación
    de elegancia en una solución, en una demostración? Es la armonía de las
    diversas partes, su simetría, su feliz equilibrio; en una palabra es todo lo
    que introduce orden, todo lo que da unidad, lo que nos permite ver claramente
    y comprender a la vez el conjunto y los detalles.
  + Todos creen firmemente en ello porque los matemáticos se imaginan que es un
    hecho de observación, y los observadores que es una teoría matemática.

+ [[https://es.wikipedia.org/wiki/Henry_David_Thoreau][Henry David Thoreau]] ::
  + No importa lo pequeño pueda parecer el comienzo: lo que se hace bien, bien
    hecho queda para siempre.

+ [[https://es.wikipedia.org/wiki/Hermann_Weyl][Hermann Weyl]] ::
  + Una prueba matemática moderna no es tan diferente de una máquina moderna:
    simples principios fundamentales están ocultos bajo una masa de detalles
    técnicos.
  + La investigación matemática eleva la mente humana a una proximidad más
    cercana a lo divino de la que se puede alcanzar a través de cualquier otro
    medio.

+ [[https://es.wikipedia.org/wiki/Hippolyte_Taine][Hippolyte Taine]] ::
  + Para conseguir algún resultado en la vida es preciso tener paciencia,
    aburrirse, hacer y deshacer, volver a empezar y seguir de nuevo, sin que un
    impulso de cólera o un arrebato de la imaginación vengan a detener o desviar
    el trabajo diario.

+ [[https://es.wikipedia.org/wiki/Horace_Walpole][Horace Walpole]] ::
  + Todo el secreto de la vida es estar interesado en una cosa profundamente y en
    otras tantas un poco.

+ [[https://es.wikipedia.org/wiki/Ian_Stewart][Ian Stewart]] ::
  + A menudo la contribución clave de la intuición es hacernos conscientes de los
    puntos débiles de un problema, lugares donde puede ser vulnerable a los
    ataques. Una prueba matemática es como una batalla, o si prefieres una
    metáfora menos belicosa, una partida de ajedrez. Una vez que se ha
    identificado un punto débil potencial, el conocimiento técnico de la
    maquinaria matemática puede aprovecharse para explotarlo.
  + La intuición matemática es la capacidad de la mente para sentir la forma y la
    estructura, para detectar patrones que no podemos percibir conscientemente. La
    intuición carece de la claridad cristalina de la lógica consciente, pero lo
    compensa al llamar la atención sobre cosas que nunca hubiéramos considerado
    conscientemente.
  + La tendencia del empresario es explotar el mundo natural. La tendencia del
    ingeniero es cambiarlo. La tendencia del científico es tratar de entenderlo, de
    averiguar qué es lo que realmente está sucediendo. La tendencia del matemático
    es estructurar ese proceso de comprensión buscando generalidades que
    atraviesen las subdivisiones obvias.

+ [[https://es.wikipedia.org/wiki/Immanuel_Kant][Immanuel Kant]] ::
  + Tan solo por la educación puede el hombre llegar a ser hombre. El hombre no es
    más que lo que la educación hace de él.

+ [[https://es.wikipedia.org/wiki/Imre_Lakatos][Imre Lakatos]] ::
  + El compromiso ciego con una teoría no es una virtud intelectual: es un crimen
    intelectual.
  + La formación científica, atomizada de acuerdo con técnicas distintas y
    separada, ha degenerado en entrenamiento científico. No hay que sorprenderse
    de que ello desanime a las mentes críticas.

+ [[https://en.wikipedia.org/wiki/Ivars_Peterson][Ivars Peterson]] ::
  + El misterio es un ingrediente ineludible de las matemáticas. Las matemáticas
    están llenas de preguntas sin respuesta, que superan con creces el número de
    teoremas y resultados conocidos. Está en la naturaleza de las matemáticas el
    plantear más problemas de los que puede resolver. De hecho, la matemática en
    sí misma puede estar construida sobre pequeñas islas de verdad que comprenden
    las piezas de la matemática que pueden ser validadas por pruebas relativamente
    cortas. Todo lo demás es especulación.

+ [[https://es.wikipedia.org/wiki/Johann_Wolfgang_von_Goethe][Johann Wolfgang von Goethe]] ::
  + Sea lo que sea que puedas o sueñes que puedas, comiénzalo. El atrevimiento
    posee genio, poder y magia. Comiénzalo ahora.

+ [[https://es.wikipedia.org/wiki/Jacques_Lacan][Jacques Lacan]] ::
  + He aquí el gran error de siempre: imaginar que los seres humanos piensan lo que

+ [[https://es.wikipedia.org/wiki/James_Joseph_Sylvester][James Joseph Sylvester]] ::
  + El objetivo constante del matemático es reducir todas sus expresiones a sus
    términos más elementales, reducir cada palabra y frase superflua, y condensar
    el máximo de significado en el mínimo de lenguaje.

+ [[https://es.wikipedia.org/wiki/Jean_Dieudonn%C3%A9][Jean Dieudonné]] ::
  + No existe un criterio de apreciación que no varíe de una época a otra y de un
    matemático a otro. [...] Estas divergencias en el gusto recuerdan las disputas
    que suscitan las obras de arte, y es un hecho de que los matemáticos a menudo
    discuten entre sí si un teorema es más o menos hermoso. Esto nunca deja de
    sorprender a los profesionales de otras ciencias: para ellos, el único
    criterio es la verdad de una teoría o fórmula.

+ [[https://es.wikipedia.org/wiki/Jean_Piaget][Jean Piaget]] ::
  + El objetivo principal de la educación es crear hombres capaces de hacer cosas
    nuevas, no simplemente repetir lo que han hecho otras generaciones, hombres
    creativos, inventivos y descubridores.

+ [[https://es.wikipedia.org/wiki/Jeff_Lindsay][Jeff Lindsay]] ::
  + La clave de una vida feliz es alcanzar metas de las que te sientas
    orgulloso y un propósito que cumplir.

+ [[https://es.wikipedia.org/wiki/John_Archibald_Wheeler][John Archibald Wheeler]] ::
  + Vivimos en una isla rodeada de un mar de ignorancia. A medida que nuestra
    isla del conocimiento crece, también crece la costa de nuestra ignorancia.

+ [[https://es.wikipedia.org/wiki/John_von_Neumann][John von Neumann]] ::
  + Se espera que un teorema matemático o una teoría matemática no sólo describa
    y clasifique de manera sencilla y elegante numerosos y a priori dispares casos
    especiales. También se espera elegancia en su estructura arquitectónica.

+ [[https://es.wikipedia.org/wiki/Jorge_Luis_Borges][Jorge Luis Borges]] ::
  + Nuestra cobardía y nuestra desidia tienen la culpa de que el mañana y el ayer
    sean iguales.

+ [[https://es.wikipedia.org/wiki/Joseph_Fourier][Joseph Fourier]] ::
  + Mathematics compares the most diverse phenomena and discovers the secret
    analogies that unite them.

+ [[https://en.wikipedia.org/wiki/Joshua_Bloch][Joshua Bloch]] ::
  + Cuanto más claro y bonito sea el programa, más rápido se ejecutará. Y si no
    lo hace, será fácil hacerlo rápido.

+ [[https://es.wikipedia.org/wiki/Jos%C3%A9_Saramago][José Saramago]] ::
  + La esperanza nunca ha sido de fiar.

+ [[https://es.wikipedia.org/wiki/Kurt_Lewin][Kurt Lewin]] ::
  + No hay nada tan práctico como una buena teoría.

+ [[https://es.wikipedia.org/wiki/Leonhard_Euler][Leonhard Euler]] ::
  + Algunos hechos se pueden ver más claramente con el ejemplo que con pruebas.
  + Las propiedades de los números conocidos hoy en día han sido descubiertas en
    su mayoría por la observación, y descubiertas mucho antes de que su verdad
    haya sido confirmada por rígidas demostraciones. Hay incluso muchas
    propiedades de los números que conocemos bien, pero que todavía no podemos
    probar; sólo las observaciones nos han llevado a su conocimiento. Por lo
    tanto, vemos que en la teoría de los números, que todavía es muy imperfecta,
    podemos poner nuestras mayores esperanzas en las observaciones.
  + Nada ocurre en el mundo cuyo significado no sea el de un máximo o un mínimo.

+ [[https://es.wikipedia.org/wiki/Leonardo_da_Vinci][Leonardo da Vinci]] ::
  + El mayor placer es la alegría de entender.
  + El que ama la práctica sin teoría es como el marinero que se embarca sin
    timón ni brújula y nunca sabe dónde puede ir.
  + La simplicidad es la máxima sofisticación.
  + Los que se enamoran de la práctica sin la teoría son como los pilotos sin timón
    ni brújula, que nunca podrán saber a dónde van.

+ [[https://es.wikipedia.org/wiki/S%C3%A9neca][Lucio Anneo Séneca]] ::
  + Enseñando aprendemos.
  + Importa mucho más lo que tú piensas de ti mismo que lo que los otros opinen de
    ti.
  + Largo es el camino de la enseñanza por medio de teorías; breve y eficaz por
    medio de ejemplos.

+ [[https://es.wikipedia.org/wiki/Ludwig_Wittgenstein][Ludwig Wittgenstein]] ::
  + El que hoy en día enseña filosofía da al otro alimentos no para complacerle,
    sino para modificar su gusto.

+ [[https://es.wikipedia.org/wiki/Mahatma_Gandhi][Mahatma Gandhi]] ::
  + La verdad es totalmente interior. No hay que buscarla fuera de nosotros ni
    querer realizarla luchando con violencia con enemigos exteriores.

+ [[https://es.wikipedia.org/wiki/Maim%C3%B3nides][Maimónides]] ::
  + Quien quiera alcanzar la perfección humana, debe estudiar primero la
    Lógica, después las distintas ramas de las Matemáticas en su orden correcto,
    luego la Física, y por último la Metafísica.

+ [[https://es.wikipedia.org/wiki/Marco_Aurelio][Marco Aurelio]] ::
  + La vida de un hombre es lo que sus pensamientos hacen de ella.

+ [[https://es.wikipedia.org/wiki/Marguerite_Duras][Marguerite Duras]] ::
  + Muy pronto en la vida es demasiado tarde.

+ [[https://es.wikipedia.org/wiki/Marie_Curie][Marie Curie]] ::
  + Nada en la vida debe ser temido, solamente comprendido. Ahora es el momento de
    comprender más, para temer menos.

+ [[https://es.wikipedia.org/wiki/Mario_Bunge][Mario Bunge]] ::
  + De todos los enemigos de la educación, uno de los peores es el pedagogo que
    asegura que el modo de enseñar es más importante que lo que se enseña.
  + Es importante enseñar a estudiar por cuenta propia, a buscar por cuenta propia,
    a asombrarse.
  + Hay que educar a la gente. No basta saber que a la tía María le fue bien con
    el acupunturista o con el homeópata, porque el efecto placebo siempre está en
    la cabecera de los enfermos. Y no sólo de los enfermos, sino también de los
    votantes.
  + Hay que formar cerebros porque solamente el cerebro bien formado puede, no
    solamente usar la técnica existente, sino mejorarla con ideas nuevas y
    originales gracias a su curiosidad y a que está investigando. Si se insiste
    con la misma información a la gente, en lugar de cultivar su curiosidad,
    terminará por aburrirse.
  + Si bien uno está contento de pertenecer a una red cultural, llega un momento
    en que se necesita más tiempo para la reflexión. De lo contrario, ésta es
    superficial, demasiado rápida, sin tiempo para asimilar, criticar,
    sopesar. Hace falta más tiempo para ensimismarse, para reflexionar en silencio
    y soledad.
  + Sólo los fanáticos odian a las personas tanto como las doctrinas. Uno puede
    ser intolerante con las teorías falsas, pero tolerante con quienes las
    sustentan, a condición de que no medren con ellas.

+ [[https://es.wikipedia.org/wiki/Martin_Fowler][Martin Fowler]] ::
  + Cualquier ignorante puede escribir un programa que un ordenador puede
    entender. Los buenos programadores escriben programas que los humanos pueden
    entender.

+ [[https://es.wikipedia.org/wiki/Maria_Montessori][María Montessori]] ::
  + Cualquier ayuda innecesaria es un obstáculo para el desarrollo.

+ [[https://es.wikipedia.org/wiki/Max_Planck][Max Planck]] ::
  + No es la posesión de la verdad, sino el éxito que acompaña a la búsqueda de
    ella, lo que enriquece al buscador y le trae la felicidad.

+ [[https://es.wikipedia.org/wiki/Michael_Atiyah][Michael Atiyah]] ::
  + Cualquier buen teorema debe tener varias pruebas, cuanto más mejor. Por dos
    razones: generalmente, las diferentes pruebas tienen diferentes fortalezas y
    debilidades, y se generalizan en diferentes direcciones: no son solo
    repeticiones entre sí.

+ [[https://es.wikipedia.org/wiki/Miguel_de_Unamuno][Miguel de Unamuno]] ::
  + Se viaja no para buscar el destino sino para huir de donde se parte.

+ [[https://es.wikipedia.org/wiki/Moli%C3%A8re][Molière]] ::
  + Las cosas sólo tienen el valor que les damos.

+ [[https://es.wikipedia.org/wiki/Morris_Kline][Morris Kline]] ::
  + Aunque los conceptos y operaciones matemáticas están formulados para
    representar aspectos del mundo físico, las matemáticas no deben identificarse
    con el mundo físico. Sin embargo, nos dice mucho sobre ese mundo si tenemos
    cuidado de aplicarlo e interpretarlo correctamente.
  + La introducción y la aceptación gradual de conceptos que no tienen
    contrapartes inmediatas en el mundo real ciertamente forzó el reconocimiento
    de que las matemáticas son una creación humana, algo arbitraria, en lugar de
    una idealización de las realidades de la naturaleza, derivadas únicamente de
    la naturaleza. Pero acompañar este reconocimiento y, de hecho, impulsar su
    aceptación fue un descubrimiento más profundo: las matemáticas no son un
    cuerpo de verdades sobre la naturaleza.
  + Las matemáticas no representan leyes inherentes al diseño del universo, sino que
    simplemente proporciona esquemas o modelos hechos por el hombre que podemos
    usar para deducir conclusiones sobre nuestro mundo sólo en la medida en que el
    modelo es una buena idealización.
  + Una prueba nos dice dónde concentrar nuestras dudas. [...] Una prueba
    elegantemente ejecutada es un poema en todo menos en la forma en que está
    escrito.

+ [[https://es.wikipedia.org/wiki/Napole%C3%B3n_Bonaparte][Napoleón Bonaparte]] ::
  + Los sabios son los que buscan la sabiduría; los necios piensan ya haberla
    encontrado.

+ [[https://es.wikipedia.org/wiki/Nicol%C3%A1s_Cop%C3%A9rnico][Nicolás Copérnico]] ::
  + Las matemáticas se escriben para los matemáticos.

+ [[https://es.wikipedia.org/wiki/Octavio_Paz][Octavio Paz]] ::
  + Cuidemos las palabras y cuidémonos de ellas.

+ [[https://es.wikipedia.org/wiki/Oliver_Heaviside][Oliver Heaviside]] ::
  + Las matemáticas son una ciencia experimental, y las definiciones no son lo
    primero, sino lo último.

+ [[https://es.wikipedia.org/wiki/Ovidio][Ovidio]] ::
  + La gota horada la roca, no por su fuerza sino por su constancia.

+ [[https://es.wikipedia.org/wiki/Paul_Dirac][Paul Dirac]] ::
  + Una teoría con belleza matemática es más probable que sea correcta que una
    fea que se ajuste a algunos datos experimentales.
  + Buena parte de mi investigación en física ha consistido en no proponerse
    resolver un problema en particular, sino simplemente examinar las cantidades
    matemáticas de un tipo que los físicos utilizan y tratar de combinarlas de
    una manera interesante.

+ [[https://es.wikipedia.org/wiki/Paul_Halmos][Paul Halmos]] ::
  + Es el deber de todos los profesores, y de los profesores de matemáticas en
    particular, exponer a sus alumnos a problemas mucho más que a hechos.
  + La alegría de aprender repentinamente un secreto anterior y la alegría de
    descubrir repentinamente una verdad desconocida hasta ahora son las mismas
    para mí. Ambas tienen el destello de la iluminación, la visión casi
    increíblemente mejorada, y el éxtasis y la euforia de la tensión liberada.
  + Las matemáticas no son una ciencia deductiva, es un cliché. Cuando se trata
    de probar un teorema, no sólo se enumeran las hipótesis, y luego se empieza a
    razonar. Lo que haces es ensayo y error, experimentación, conjeturas.
  + Las matemáticas no son una ciencia deductiva, es un cliché. Cuando se trata
    de probar un teorema, no sólo se enumeran las hipótesis, y luego se empieza a
    razonar. Lo que se hace es ensayo y error, experimentación, conjeturas.
  + No sólo lo leas; ¡lucha! Haz tus propias preguntas, busca tus propios
    ejemplos, descubre tus propias pruebas.
  + Un profesor que no siempre está pensando en resolver problemas -de los que no
    conoce la respuesta- simplemente no está psicológicamente preparado para
    enseñarles a sus alumnos a resolver problemas.
  + Una buena cantidad de ejemplos, tan grande como sea posible, es indispensable
    para una comprensión completa de cualquier concepto, y cuando quiero aprender
    algo nuevo, mi primer trabajo es construir uno.

+ [[https://en.wikipedia.org/wiki/A_Mathematician%27s_Lament][Paul Lockhart]] ::
  + Hacer matemáticas siempre debe significar encontrar patrones y crear
    explicaciones hermosas y significativas.
  + La agudeza mental de cualquier tipo proviene de resolver problemas por ti
    mismo, no de que te digan cómo resolverlos.
  + La enseñanza no se limita a la información. Se trata de tener una relación
    intelectual honesta con tus alumnos.
  + Las matemáticas son el arte de la explicación. Si les niega a los estudiantes
    la oportunidad de participar en esta actividad, de plantear sus propios
    problemas, de hacer sus propias conjeturas y descubrimientos, de equivocarse,
    de frustrarse creativamente, de inspirarse y de preparar sus propias
    explicaciones y pruebas, les niega la matemática misma.
  + Si hay algo así como un principio estético unificador en matemáticas, es
    este: lo simple es hermoso. Los matemáticos disfrutan pensando en las cosas
    más simples posibles, y las más simples son fantásticas.
  + Un buen problema es algo que no sabes cómo resolver. Eso es lo que lo hace un
    buen rompecabezas y una buena oportunidad.

+ [[https://es.wikipedia.org/wiki/Paulo_Freire][Paulo Freire]] ::
  + No habría creatividad sin la curiosidad que nos mueve y que nos pone
    pacientemente impacientes ante el mundo que no hicimos, al que acrecentamos con
    algo que hacemos.

+ [[https://es.wikipedia.org/wiki/Philip_K._Dick][Philip K. Dick]] ::
  + La herramienta básica para la manipulación de la realidad es la manipulación
    de las palabras. Si puedes controlar el significado de las palabras, puedes
    controlar a la gente que debe usar las palabras.

+ [[https://es.wikipedia.org/wiki/Plat%C3%B3n][Platón]] ::
  + El matemático es perfecto sólo en la medida en que es un hombre perfecto, en
    la medida en que siente en sí mismo la belleza de la verdad; sólo entonces su
    trabajo será minucioso, transparente, prudente, puro, claro y elegante.

+ Proverbio persa ::
  + Aprende lo que te parezca difícil: todo lo difícil se vuelve fácil gracias al
    aprendizaje.

+ [[https://es.wikipedia.org/wiki/P%C3%ADo_Baroja][Pío Baroja]] ::
  + A una colectividad se le engaña siempre mejor que a un hombre.

+ [[https://es.wikipedia.org/wiki/Rabindranath_Tagore][Rabindranath Tagore]] ::
  + Ese que habla tanto está completamente hueco, ya sabes que el cántaro vacío es
    el que más suena.

+ [[https://en.wikipedia.org/wiki/Raymond_S._Nickerson][Raymond S. Nickerson]] ::
  + Además de considerar las matemáticas como el estudio de patrones, las
    matemáticas pueden ser vistas, pragmáticamente, como una vasta colección de
    problemas de ciertos tipos y de enfoques que han demostrado ser efectivos para
    resolverlos.
  + Sin negar la utilidad de la distinción entre intuición y prueba, creo que se
    puede hacer con demasiada agudeza; la intuición desempeña un papel esencial en
    la elaboración y evaluación de las pruebas y a veces se modifica como
    consecuencia de estos procesos. En este sentido, la distinción es como la del
    pensamiento creativo y el pensamiento crítico; aunque esta distinción también
    es útil, no es posible tenerla en un sentido muy satisfactorio sin el
    otro.

+ [[https://es.wikipedia.org/wiki/Remy_de_Gourmont][Remy de Gourmont]] ::
  + El hombre no asocia ideas de acuerdo a la lógica o verificable exactitud, sino
    de acuerdo a su gusto e intereses. Es por esta razón que la mayoría de las
    verdades no son nada más que prejuicios.

+ [[https://es.wikipedia.org/wiki/Ren%C3%A9_Descartes][René Descartes]] ::
  + Cada problema que resolví se convirtió en una regla que sirvió después para
    resolver otros problemas. Así, cada verdad descubierta era una regla
    disponible en el descubrimiento de las siguientes.
  + Cuando surge un problema, deberíamos ser capaces de ver pronto si será rentable
    examinar otros problemas primero, y qué otros, y en qué orden.
  + Para buscar la verdad, es necesario, una vez en el curso de nuestra vida,
    dudar, en la medida de lo posible, de todas las cosas.

+ [[https://es.wikipedia.org/wiki/Richard_Courant][Richard Courant]] y [[https://en.wikipedia.org/wiki/Herbert_Robbins][Herbert Robbins]] ::
  + El hecho de que la prueba de un teorema consista en la aplicación de ciertas
    reglas simples de lógica no elimina el elemento creativo en las matemáticas,
    que radica en la elección de las posibilidades a examinar.
  + La matemática como expresión de la mente humana refleja la voluntad activa,
    la razón contemplativa y el deseo de perfección estética. Sus elementos
    básicos son la lógica y la intuición, el análisis y la construcción, la
    generalidad y la individualidad. Aunque diferentes tradiciones pueden
    enfatizar diferentes aspectos, es solo la interacción de estas fuerzas
    antitéticas y la lucha por su síntesis lo que constituye la vida, la utilidad
    y el valor supremo de la ciencia matemática.

+ [[https://es.wikipedia.org/wiki/Richard_Hamming][Richard Hamming]] ::
  + El propósito de la computación es la comprensión, no los números.

+ [[https://es.wikipedia.org/wiki/Richard_Feynman][Richard Feynman]] ::
  + La mejor enseñanza sólo puede hacerse cuando hay una relación individual
    directa entre un estudiante y un buen profesor: una situación en la que el
    estudiante discute las ideas, piensa sobre las cosas y habla sobre las cosas. Es
    imposible aprender mucho asistiendo simplemente a una lección, o incluso
    haciendo simplemente los problemas que se proponen.
  + Para aquellos que no conocen las matemáticas, es difícil sentir la belleza, la
    profunda belleza de la naturaleza... Si quieres aprender sobre la naturaleza,
    apreciar la naturaleza, es necesario aprender el lenguaje en el que habla.
  + Una medida de nuestro entendimiento es el número de formas independientes de
    llegar al mismo resultado.

+ [[https://es.wikipedia.org/wiki/Robert_A._Heinlein][Robert A. Heinlein]] ::
  + Puedes convencer a mil hombres apelando a sus prejuicios más rápidamente que
    a uno solo utilizando la lógica.

+ [[https://es.wikipedia.org/wiki/Roger_Penrose][Roger Penrose]] ::
  + La comprensión es, después de todo, de lo que se trata la ciencia, y la
    ciencia es mucho más que la computación sin sentido.
  + Una idea hermosa tiene muchas más posibilidades de ser una idea correcta que
    una fea.

+ [[https://es.wikipedia.org/wiki/Ronald_David_Laing][Ronald David Laing]] ::
  + Deberíamos dedicarnos a desaprender gran parte de lo aprendido y aprender lo
    que no se nos ha enseñado.

+ [[https://es.wikipedia.org/wiki/Agust%C3%ADn_de_Hipona][San Agustín]] ::
  + Los hombres están siempre dispuestos a curiosear y averiguar sobre las vidas
    ajenas, pero les da pereza conocerse a sí mismos y corregir su propia vida.

+ [[https://es.wikipedia.org/wiki/Santiago_Ram%C3%B3n_y_Cajal][Santiago Ramón y Cajal]] ::
  + ¿No tienes enemigos? ¿Es que jamás dijiste la verdad o jamás amaste la
    justicia?

+ [[https://es.wikipedia.org/wiki/Sexto_Pomponio][Sexto Pomponio]] ::
  + Algunos hasta tal punto se refugian en la oscuridad que consideran confuso
    cuanto es luminoso

+ [[https://es.wikipedia.org/wiki/Sigmund_Freud][Sigmund Freud]] ::
  + ¡Estudia! No para saber una cosa más, sino para saberla mejor.

+ [[https://es.wikipedia.org/wiki/Simone_de_Beauvoir][Simone de Beauvoir]] ::
  + La representación del mundo, como el mundo mismo, es obra de los hombres; la
    describen desde su propio punto de vista, que confunden con la verdad
    absoluta.

+ [[https://es.wikipedia.org/wiki/Stanis%C5%82aw_Ulam][Stanislaw M Ulam]] ::
  + El lado estético de las matemáticas ha sido de una importancia abrumadora a
    lo largo de su desarrollo. Lo que importa no es si un teorema es útil, sino lo
    elegante que es.
  + En muchos casos, las matemáticas son un escape de la realidad. El matemático
    encuentra su propio nicho monástico y felicidad en actividades que están
    desconectadas de los asuntos externos. Algunos lo practican como si usaran una
    droga. El ajedrez a veces juega un papel similar. En su descontento por los
    acontecimientos de este mundo, algunos se sumergen en una especie de autarquía
    en matemáticas.
  + ¿Qué es exactamente la matemática? Muchos lo han intentado, pero nadie ha
    logrado definir las matemáticas; siempre es otra cosa.

+ [[https://es.wikipedia.org/wiki/Steve_Jobs][Steve Jobs]] ::
  + Learning to program teaches you how to think. Computer science is a liberal
    art.

+ [[https://es.wikipedia.org/wiki/S%C3%B3crates][Sócrates]] ::
  + La ciencia humana consiste más en destruir errores que en descubrir verdades.

+ [[https://en.wikipedia.org/wiki/Tony_Hoare][Tony Hoare]] ::
  + Inside every large program is a small program trying to get out.

+ [[https://es.wikipedia.org/wiki/Umberto_Eco][Umberto Eco]] ::
  + No todas las verdades son para todos los oídos.

+ [[https://es.wikipedia.org/wiki/Victor_Hugo][Victor Hugo]] ::
  + El agua que no corre hace un pantano; la mente que no trabaja hace un tonto.

+ [[https://es.wikipedia.org/wiki/Voltaire][Voltaire]] ::
  + A los tontos todo les maravilla en un autor apreciado; pero yo, que leo para
    mí, sólo apruebo lo que me gusta.
  + El cerebro humano es un órgano complejo con el maravilloso poder de
    permitirle al hombre encontrar razones para seguir creyendo lo que sea que
    quiera creer.
  + En geometría, como en la mayoría de las ciencias, es muy raro que una
    proposición aislada sea de utilidad inmediata. Pero las teorías más poderosas
    en la práctica están formadas por proposiciones que sólo la curiosidad sacó a
    la luz, y que durante mucho tiempo permanecieron inútiles sin poder adivinar
    de qué manera deberían dejar de serlo un día. En este sentido, se puede decir
    que en la ciencia real, ninguna teoría, ninguna investigación, es en efecto
    inútil.
  + Los prejuicios son la razón de los tontos.

+ [[https://es.wikipedia.org/wiki/Wilhelm_von_Humboldt][Wilhelm von Humboldt]] ::
  + La interdependencia entre el pensamiento y la palabra ilumina claramente la
    verdad de que las lenguas no son realmente un medio para representar verdades
    ya conocidas, sino más bien un instrumento para descubrir verdades no
    reconocidas anteriormente. Las diferencias entre los lenguajes no son las de
    los sonidos y los signos, sino las de las diferentes cosmovisiones.

+ [[https://es.wikipedia.org/wiki/William_James][William James]] ::
  + Cuando debemos hacer una elección y no la hacemos, esto ya es una
    elección.
  + El arte de ser sabio es el arte de saber qué pasar por alto.
  + El objetivo de la ciencia es siempre reducir la complejidad a la
    simplicidad.
  + Primero se ataca una nueva teoría por absurda; luego se admite que es cierta,
    pero obvia e insignificante; finalmente se la considera tan importante que sus
    adversarios afirman que ellos mismos la descubrieron.

+ [[https://es.wikipedia.org/wiki/William_Thurston][William Thurston]] ::
  + Las matemáticas son increíblemente comprimibles: puede que tenga que luchar
    mucho tiempo, paso a paso, para trabajar en algún proceso o idea desde varios
    enfoques. Pero una vez que realmente lo entiendes y tienes la perspectiva
    mental para verlo como un todo, hay una tremenda compresión mental. Puedes
    archivarlo, recuperarlo rápida y completamente cuando lo necesites, y usarlo
    como un solo paso en algún otro proceso mental. La idea que acompaña a esta
    compresión es una de las verdaderas alegrías de las matemáticas.
  + Las matemáticas no tratan de números, ecuaciones, cálculos o algoritmos: se
    trata de entender.

+ [[https://en.wikipedia.org/wiki/Yunmen_Wenyan][Yunmen Wenyan]] ::
  + Si tu mente no está nublada por cosas innecesarias, esta es la mejor estación
    de tu vida.

+ [[https://es.wikipedia.org/wiki/Zhuangzi][Zhuangzi]] ::
  + El buen orden resulta espontáneamente cuando se dejan las cosas a sí mismas.
  + Los pies pisan el suelo; pero es aquello que no pisan lo que permite
    caminar. Aquello que se conoce es poco; pero, apoyado en lo poco que se conoce
    es posible conocer mucho.
  + Un camino se hace caminando sobre él.
  + Un pequeño saber no puede equipararse a uno grande. Ni una corta vida a una
    larga existencia. ¿Cómo se sabe que esto es así? El hongo que sólo vive una
    mañana desconoce el ciclo de la luna. La cigarra de verano nada sabe de
    primaveras ni de otoños. Así son las pequeñas existencias.
  + Una rana en un pozo no puede concebir el océano.
