#+TITLE: Pensamientos matemáticos

* Ordenados por autor
** [[https://es.wikipedia.org/wiki/Alain_Badiou][Alain Badiou]]

+ Las matemáticas fueron y siguen siendo muy importantes para la filosofía,
  porque son el ejemplo tipo de un lenguaje cuya Verdad es independiente del
  poder. Lo enunciado se demuestra o no se demuestra. No hay rey o clérigo que
  valga. Es, en cierto sentido, el primer pensamiento democrático, sometido a
  examen colectivo.

** [[https://es.wikipedia.org/wiki/Alan_Turing][Alan Turing]]

+ Las máquinas me sorprenden con mucha frecuencia.

+ Los programas son rompecabezas. Un juego, como cualquier otro juego.

+ Para que el hombre que hace la comprobación no tenga una tarea demasiado
  difícil, el programador debe hacer una serie de afirmaciones definidas que
  puedan ser comprobadas individualmente, y de las que se desprenda fácilmente
  la corrección de todo el programa.

** [[https://bit.ly/39mhQEZ][André Weil]]

+ El matemático seguirá su camino en la seguridad de que podrá saciar su sed en
  las mismas fuentes del conocimiento, convencido de que éstas no cesarán de
  fluir, puras y abundantes, mientras que los demás habrán de recurrir a las aguas
  cenagosas de una sórdida realidad. Si se le reprochase al matemático la soberbia
  de su actitud, si se le reclamase su colaboración, si se le demandase porqué se
  recluye en los altos glaciares a los que nadie salvo los de su clase le puede
  seguir, él contestaría, con Jacobi: *Por el honor del espíritu humano*.

+ El rigor es para el matemático lo que la moral es para el hombre. No consiste
  en probarlo todo, sino en mantener una distinción clara entre lo que se supone
  y lo que se prueba, y en tratar de asumir lo menos posible en cada etapa.

+ En el futuro, como en el pasado, las grandes ideas [de las matemáticas] deben
  ser ideas simplificadoras, el creador debe ser siempre el que aclare, para sí
  mismo y para los demás, los temas más complicados de las fórmulas y los
  conceptos.

+ Nada es más fructífero -todos los matemáticos lo saben- que esas oscuras
  analogías, esos reflejos inquietantes de una teoría sobre otra; esas caricias
  furtivas, esas discordias inexplicables; nada da también más placer al
  investigador. Llega el día en que esta ilusión se disuelve: el presentimiento
  se convierte en certeza; las teorías unidas revelan su fuente común antes de
  desaparecer.

** [[https://es.wikipedia.org/wiki/Antoine_Lavoisier][Antoine Lavoisier]]

+ Pensamos solo por medio de las palabras. Los idiomas son verdaderos métodos
  analíticos. El álgebra, que se adapta a su propósito en cada especie de
  expresión, de la manera más simple, más exacta y mejor posible, es al mismo
  tiempo un idioma y un método analítico. El arte del razonamiento no es más que
  un lenguaje bien organizado.

** [[https://es.wikipedia.org/wiki/Arthur_C._Clarke][Arthur C. Clarke]]

+ Cualquier tecnología suficientemente avanzada es indistinguible de la magia.

** [[https://en.wikipedia.org/wiki/Brian_Kernighan][Brian Kernighan]]

+ El control de la complejidad es la esencia de la programación informática.

** [[https://en.wikipedia.org/wiki/Buckminster_Fuller][Buckminster Fuller]]

+ When I am working on a problem, I never think about beauty. I think only of
  how to solve the problem. But when I have finished, if the solution is not
  beautiful, I know it is wrong.
  + Cuando estoy trabajando en un problema, nunca pienso en la belleza. Sólo
    pienso en cómo resolver el problema. Pero cuando he terminado, si la
    solución no es bella, sé que está mal.

** [[https://es.wikipedia.org/wiki/Carl_Benjamin_Boyer][Carl B. Boyer]] y [[https://en.wikipedia.org/wiki/Uta_Merzbach][Uta C. Merzbach]]

+ Una de las lecciones que la historia de las matemáticas nos enseña claramente
  es que la búsqueda de soluciones a problemas no resueltos, ya sean
  solucionables o no, conduce invariablemente a importantes descubrimientos en
  el camino.

** [[https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss][Carl Friedrich Gauss]]

+ El verdadero objetivo de la ciencia es el honor de la mente humana.

+ Las matemáticas son la reina de las ciencias y la teoría de los números es la
  reina de las matemáticas.

+ Los encantos de esta ciencia sublime, las matemáticas, sólo se le revelan a
  aquellos que tienen el valor de profundizar en ella.

+ No es el conocimiento, sino el acto de aprendizaje, y no la posesión, sino
  el acto de llegar allí, que concede el mayor disfrute.

+ Sabe que escribo lentamente. Esto se debe sobre todo a que no quedo satisfecho
  hasta que no consigo decir todo cuanto me sea posible en unas pocas palabras, y
  escribir de modo conciso lleva mucho más tiempo que hacerlo en extensión.

** [[https://en.wikipedia.org/wiki/Carl_Gustav_Jakob_Jacobi][Carl Gustav Jacob Jacobi]]

+ M Fourier opinaba que la finalidad primordial de las matemáticas consistía
  en su utilidad pública y en la explicación de los fenómenos naturales; pero un
  filósofo como él debería haber sabido que la finalidad única de la ciencia es la
  de rendir honor al espíritu humano y que por ello una cuestión sobre números
  vale tanto como una cuestión sobre el sistema del mundo.

+ Siempre se debe generalizar.

** [[https://bit.ly/33ZqDvB][Charles S Peirce]]

+ La matemática es la más abstracta de todas las ciencias. Porque no hace
  observaciones externas, ni afirma nada como un hecho real. Cuando el
  matemático trata con los hechos, se convierten para él en meras hipótesis;
  porque con su verdad se niega a preocuparse él mismo. Toda la ciencia de las
  matemáticas es una ciencia de hipótesis, de modo que nada podría ser más
  completamente abstraído de la realidad concreta.

** [[https://bit.ly/2UIadEK][Clifford Truesdell]]

+ La simplicidad no viene por sí misma sino que debe ser ser creada.

** [[https://en.wikipedia.org/wiki/David_Gelernter][David Gelernter]]

+ Beauty is more important in computing than anywhere else in technology because
  software is so complicated. Beauty is the ultimate defense against complexity.

** [[https://en.wikipedia.org/wiki/David_Hilbert][David Hilbert]]

+ It is an error to believe that rigor in a proof is an enemy of simplicity. On
  the contrary we find it confirmed by numerous examples that the rigorous
  method is, at the same time, the simpler and the more easily comprehended.
  The very effort for rigor forces us to find the simpler methods of proof.
  + Es un error creer que el rigor es enemigo de la sencillez. Al contrario,
    encontramos confirmado por numerosos ejemplos que el método riguroso es al
    mismo tiempo el más simple y el más fácil de comprender. El propio esfuerzo
    por el rigor nos obliga a descubrir métodos de prueba más sencillos.

+ Mathematics is a game played according to certain rules with meaningless
  marks on paper.

+ The art of doing mathematics is finding that special case that contains all
  the germs of generality.

+ The finest product (Cantor's work on set theory) of mathematical genius and
  one of the supreme achievments of purly intellectual human activity.

+ Un problema matemático debería ser difícil para seducirnos, pero no
  completamente inaccesible, para que no se burle de nuestros esfuerzos. Debería
  ser para nosotros una guía en el laberíntico camino hacia las verdades ocultas
  y, en última instancia, un recordatorio de nuestro placer en la solución
  exitosa.

+ Una teoría matemática no debe considerarse completa hasta que la hayas dejado
  tan clara que puedas explicársela al primer hombre con el que te encuentres en
  la calle.

+ We must know, we will know.
  + Wir müssen wissen, wir werden wissen

+ You know, for a mathematician, he did not have enough imagination. But he has
  become a poet and now he is fine.

** [[https://en.wikipedia.org/wiki/Donald_Knuth][Donald Knuth]]

+ Let us change our traditional attitude to the construction of programs:
  Instead of imagining that our main task is to instruct a computer what to do,
  let us concentrate rather on explaining to human beings what we want a
  computer to do. (tw 8-Jan-22)
  + Cambiemos nuestra actitud tradicional en la construcción de programas. En
    lugar de imaginar que nuestra tarea principal es indicarle a una computadora
    lo que debe hacer, concentrémonos más bien en explicarle a los seres humanos
    lo que queremos que haga una computadora.

+ Computer programming is an art, because it applies accumulated knowledge to
  the world, because it requires skill and ingenuity, and especially because it
  produces objects of beauty. A programmer who subconsciously views himself as
  an artist will enjoy what he does and will do it better.
  + La programación de computadoras es un arte, porque aplica el conocimiento
    acumulado al mundo, porque requiere habilidad e ingenio, y especialmente
    porque produce objetos de belleza. Un programador que subconscientemente se ve
    a sí mismo como un artista disfrutará lo que hace y lo hará mejor.

+ El proceso de preparación de programas para una computadora digital es
  especialmente atractivo, no solo porque puede ser gratificante económica y
  científicamente, sino también porque puede ser una experiencia estética muy
  parecida a la composición de poesía o música.

+ El verdadero problema es que los programadores han pasado demasiado tiempo
  preocupándose por la eficiencia en los lugares equivocados y en los momentos
  equivocados; la optimización prematura es la raíz de todo mal (o al menos la
  mayor parte) en la programación.

+ La diferencia entre el arte y la ciencia es que la ciencia es lo que la gente
  entiende lo suficientemente bien como para explicarle a una computadora. Todo
  lo demás es arte.

+ The best theory is inspired by practice. The best practice is inspired by
  theory.
  + La mejor teoría está inspirada en la práctica. La mejor práctica está
    inspirada en la teoría.

+ Science is what we understand well enough to explain to a computer. Art is
  everything else we do.
  + La ciencia es lo que entendemos lo suficientemente bien como para explicarle
    a una computadora. El arte es todo lo demás que hacemos.

** [[https://en.wikipedia.org/wiki/Edsger_W._Dijkstra][Edsger W. Dijkstra]]

+ Es imposible afinar un lápiz con una cuchilla desafilada. Es igualmente inútil
  tratar de hacerlo con diez.

+ The art of programming is the art of organizaing complexity, of mastering
  multitude and avoiding its bastard chaos.
  + El arte de la programación es el arte de organizar la complejidad, de dominar
    la multitud y evitar su caos bastardo.

+ The lurking suspicion that something could be simplified is the world's
  richest source of rewarding challenges.

+ The purpose of logic is not to mimic verbal reasoning but to provide a
  calculational alternative.

** [[https://en.wikipedia.org/wiki/Edward_Kasner][Edward Kasner]] y [[https://en.wikipedia.org/wiki/James_R._Newman][James R. Newman]]

+ Mathematics is the science which uses easy words for hard ideas.
  + Las matemáticas es la ciencia que utiliza palabras fáciles para las ideas
    difíciles.

** [[https://bit.ly/2yjhMJu][Élie Cartan]]

+ Más que cualquier otra ciencia, las matemáticas se desarrollan a través de
  una secuencia de abstracciones consecutivas. El deseo de evitar errores obliga
  a los matemáticos a encontrar y aislar la esencia de los problemas y las
  entidades consideradas. Llevado al extremo, este procedimiento justifica la
  broma conocida de que un matemático es un científico que no sabe ni de qué
  está hablando ni si lo que está hablando existe o no.

** [[https://es.wikipedia.org/wiki/Emmy_Noether][Emmy Noether]]

+ Si pudiéramos ser educados dejando al margen lo que la gente piense o deje de
  pensar, y teniendo en cuenta solo lo que en principio es bueno o malo, ¡qué
  diferente sería todo!

** [[https://en.wikipedia.org/wiki/Enrico_Bombieri][Enrico Bombieri]]

+ Cuando las cosas se vuelven demasiado complicadas, a veces tiene sentido parar
  y preguntarse: ¿he planteado la pregunta correcta?

** [[https://en.wikipedia.org/wiki/Eric_Temple_Bell][Eric Temple Bell]]

+ La abstracción, a veces lanzada como un reproche a las matemáticas, es su
  principal gloria y su título más seguro de utilidad práctica. También es la
  fuente de la belleza que puede surgir de las matemáticas.

+ Obvious is the most dangerous word in mathematics.
  + Obvio es la palabra más peligrosa de las matemáticas.

+ Uno de los aspectos más atractivos de las matemáticas es que sus paradojas más
  complejas se convierten en hermosas teorías.

** [[https://en.wikipedia.org/wiki/Euclid][Euclid of Alexandria]]

+ There is no royal road to geometry.

** [[https://en.wikipedia.org/wiki/Felix_Klein][Felix Klein]]

+ Everyone knows what a curve is, until he has studied enough mathematics to
  become confused through the countless number of possible exceptions.
  + Todo el mundo sabe lo que es una curva, hasta que ha estudiado suficientes
    matemáticas para confundirse a través del incontable número de posibles
    excepciones.

** [[https://en.wikipedia.org/wiki/G._H._Hardy][G. H. Hardy]]

+ A mathematician, like a painter or poet, is a maker of patterns. If his
  patterns are more permanent than theirs, it is because they are made with
  ideas.
  + Un matemático, como un pintor o un poeta, es un creador de
    patrones. [...]. Los patrones del matemático, como el del pintor o el del
    poeta, deben ser hermosos; las ideas, como los colores o las palabras, deben
    encajar juntas de manera armoniosa. La belleza es la primera prueba: no hay
    lugar permanente en el mundo para las matemáticas feas.

+ I am interested in mathematics only as a creative art.

+ Los jóvenes deben probar los teoremas, los viejos deben escribir libros.

+ Reductio ad absurdum, which Euclid loved so much, is one of a mathematician’s
  finest weapons. It is a far finer gambit than any chess play: a chess player
  may offer the sacrifice of a pawn or even a piece, but a mathematician offers
  the game.

+ The mathematician's patterns, like the painter's or the poet's must be
  beautiful; the ideas, like the colors or the words must fit together in a
  harmonious way. Beauty is the first test: there is no permanent place in this
  world for ugly mathematics.
  + Los patrones del matemático, como los del pintor o el poeta deben ser
    hermosos; las ideas, como los colores o las palabras deben encajar de manera
    armoniosa. La belleza es la primera prueba: no hay lugar permanente en este
    mundo para las matemáticas feas.

** [[https://en.wikipedia.org/wiki/Georg_Cantor][Georg Cantor]]

+ In mathematics, the art of asking questions is more valuable than solving
  problems.
  + En matemáticas, el arte de hacer preguntas es más valioso que la resolución
    de problemas.

+ Mathematics is entirely free in its development, and its concepts are only
  linked by the necessity of being consistent, and are co-ordinated with
  concepts introduced previously by means of precise definitions.

+ The essence of mathematics is its freedom.
  + La esencia de la matemática es su libertad.

** [[https://en.wikipedia.org/wiki/Georg_Gottlob][Georg Gottlob]]

+ Computer Science as the continuation of Logic by other means. (tw 9-Jan-22)
  + La ciencia de la computación es la continuación de la lógica por otros medios.

** [[https://en.wikipedia.org/wiki/George_Boole][George Boole]]

+ No matter how correct a mathematical theorem may appear to be, one ought
  never to be satisfied that there was not something imperfect about it until
  it also gives the impression of being beautiful.
  + Por muy correcto que parezca un teorema matemático, nunca hay que
    conformarse con que no haya algo imperfecto en él hasta que también dé la
    impresión de ser bello.

** [[https://en.wikipedia.org/wiki/George_P%C3%B3lya][George Pólya]]

+ Hay que conjeturar el teorema matemático antes de probarlo: hay que planificar
  la idea de la prueba antes de completar los detalles. Hay que combinar las
  observaciones y seguir analogías: hay que intentarlo y volverlo a intentar. El
  resultado del trabajo creativo del matemático es el razonamiento demostrativo,
  una prueba; pero la prueba es descubierta por el razonamiento plausible, por
  la suposición.

+ A GREAT discovery solves a great problem but there is a grain of discovery in
  any problem.
  + Un gran descubrimiento resuelve un gran problema, pero hay un grano de
    descubrimiento en cualquier problema.

+ Ayúdate y Dios te ayudará.

+ Beauty in mathematics is seeing the truth without effort.

+ Corremos menos peligro de equivocarnos si no perdemos de vista nuestra
  meta.

+ Debemos hacer lo que podemos si no podemos hacer lo que queremos.

+ Debes adivinar el teorema matemático antes de demostrarlo: debes adivinar la
  idea de la prueba antes de llevar a cabo los detalles. Debe combinar
  observaciones y seguir analogías: debe intentarlo e intentarlo nuevamente. El
  resultado del trabajo creativo del matemático es un razonamiento demostrativo,
  una prueba; pero la prueba se descubre por razonamiento plausible.

+ El fin sugiere los medios.

+ El necio ve el principio, el sabio el final.

+ El objeto de la pesca no es tirar el anzuelo sino sacar el pez.

+ El sabio empieza por el final, el necio termina en el principio.

+ Geometry is the science of correct reasoning on incorrect figures.

+ If there is a problem you can't solve, then there is an easier  problem you
  can't solve: find it.

+ It is better to solve one problem five different ways, than to solve five
  problems one way.
  + Es mejor resolver un problema de cinco maneras diferentes, que resolver
    cinco problemas de una sola manera.

+ La belleza en las matemáticas es ver la verdad sin esfuerzo.

+ La perseverancia mata la caza.

+ La primera regla del descubrimiento es tener inteligencia y buena suerte. La
  segunda regla del descubrimiento es sentarse y esperar hasta que se tenga una
  idea brillante.

+ Mathematics has two faces: it is the rigorous science of Euclid, but it is
  also something else. Mathematics presented in the Euclidean way appears as a
  systematic, deductive science; but mathematics in the making appears as an
  experimental, inductive science. Both aspects are as old as the science of
  mathematics itself.
  + Las matemáticas tienen dos caras: son la ciencia rigurosa de Euclides, pero
    también son algo más. La matemática presentada a la manera euclidiana
    aparece como una ciencia sistemática y deductiva; pero la matemática en
    ciernes aparece como una ciencia experimental e inductiva. Ambos aspectos
    son tan antiguos como la propia ciencia de las matemáticas.

+ Mire alrededor suyo cuando encuentre la primera seta: las setas como los
  descubrimientos no crecen nunca solas.

+ No crea nada, pero reserve sus dudas para las cosas importantes.

+ No piensa bien quien no piensa dos veces.

+ No se derriba un roble de un hachazo.

+ Las matemáticas consisten en contenido y conocimiento. ¿Qué es el conocimiento
  en matemáticas? La capacidad de resolver problemas.

+ Para enseñar de manera efectiva, un profesor debe desarrollar un sentimiento
  por su asignatura; no puede hacer que sus alumnos sientan su vitalidad si no
  la siente él mismo. No puede compartir su entusiasmo cuando no tiene
  entusiasmo que compartir. La forma en que expone su tema puede ser tan
  importante como el tema que expone; debe sentir personalmente que es
  importante.

+ Quien mal comprende, mal responde.

+ Resolver problemas se puede considerar como la actividad humana más
  característica.

+ Según el viento, la vela. Según la tela, el traje.

+ Si el fin perseguido no está claro en nuestra mente, perderemos fácilmente
  el camino y abandonaremos el problema.

+ Solving problems is a practical skill like, let us say, swimming. We acquire
  any practical skill by imitation and practice. Trying to swim, you imitate
  what other people do with their hands and feet to keep their heads above
  water, and, finally, you learn to swim by practicing swimming. Trying to
  solve problems, you have to observe and to imitate what other people do when
  solving problems, and, finally, you learn to do problems by doing them.
  + La resolución de problemas es una habilidad práctica como, digamos, la
    natación. Adquirimos cualquier habilidad práctica por imitación y
    práctica. Tratando de nadar, imitas lo que otras personas hacen con sus
    manos y pies para mantener sus cabezas sobre el agua, y, finalmente,
    aprendes a nadar practicando la natación. Al intentar resolver problemas,
    hay que observar e imitar lo que hacen otras personas al resolver problemas
    y, finalmente, se aprende a resolver problemas haciéndolos.

+ Sus cinco mejores amigos son qué, por qué, dónde, cuándo y cómo.

+ The elegance of a theorem is directly proportional to the number of ideas you
  can see in it and inversely proportional to the effort it take to see them.
  + La elegancia de un teorema es directamente proporcional al número de ideas
    que puedes ver en él e inversamente proporcional al esfuerzo que requiere
    verlas.

+ The first rule of discovery is to have brains and good luck. The second rule
  of discovery is to sit tight and wait till you get a bright idea.
  + La primera regla del descubrimiento es tener inteligencia y buena suerte. La
    segunda regla del descubrimiento es sentarse y esperar hasta que se tenga una
    idea brillante.

+ The first and foremost duty of the high school in teaching mathematics is to
  emphasize methodical work in problem solving... The teacher who wishes to serve
  equally all his students, future users and nonusers of mathematics, should
  teach problem solving so that it is about one-third mathematics and
  two-thirds common sense.

+ The open secret of real success is to throw your whole personality at a
  problem.

+ To teach effectively a teacher must develop a feeling for his subject; he
  cannot make his students sense its vitality if he does not sense it
  himself. He cannot share his enthusiasm when he has no enthusiasm to
  share. How he makes his point may be as important as the point he makes; he
  must personally feel it to be important.

** [[https://en.wikipedia.org/wiki/Gian-Carlo_Rota][Gian-Carlo Rota]]

+ El ejemplo más común de belleza en matemáticas es un paso brillante en una
  prueba que de otra manera no sería distinguida. Un teorema hermoso puede no
  ser bendecido con una prueba igualmente hermosa; con frecuencia aparecen
  teoremas hermosos con pruebas feas. Cuando a un teorema hermoso le falta una
  prueba hermosa, los matemáticos intentan proporcionar nuevas pruebas que
  coincidan con la belleza del teorema, con éxito variable. Sin embargo, es
  imposible encontrar pruebas hermosas de teoremas que no sean
  hermosos.

+ La lógica matemática no trata de la verdad, sino del juego de la verdad.

+ Un buen maestro no enseña hechos, enseña entusiasmo, apertura de mente y
  valores.

+ The progress of mathematics can be viewed as progress from the infinite to
  the finite.
  + El avance de las matemáticas puede ser visto como un progreso de lo infinito
    a lo finito.

** [[https://en.wikipedia.org/wiki/G%C3%B6sta_Mittag-Leffler][Gösta Mittag-Leffler]]

+ The mathematician's best work is art, a high perfect art, as daring as the
  most secret dreams of imagination, clear and limpid. Mathematical genius and
  artistic genius touch one another.
  + La mejor obra del matemático es el arte, un arte altamente perfecto, tan
    audaz como los más secretos sueños de la imaginación, claro y límpido. El
    genio matemático y el genio artístico se tocan mutuamente.

** [[https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz][Gottfried Wilhelm Leibniz]]

+ Nothing is more important than to see the sources of invention which are, in
  my opinion more interesting than the inventions themselves.

+ The pleasure we obtain from music comes from counting, but counting
  unconsciously. Music is nothing but unconscious arithmetic.
  + El placer que obtenemos de la música proviene de contar, pero contando
    inconscientemente. La música no es más que aritmética inconsciente.

** [[https://en.wikipedia.org/wiki/Gottlob_Frege][Gottlob Frege]]

+ Every good mathematician is at least half a philosopher, and every good
  philosopher is at least half a mathematician.
  + Todo buen matemático es al menos medio filósofo, y todo buen filósofo es al
    menos medio matemático.

+ [[https://es.wikipedia.org/wiki/Grace_Murray_Hopper][Grace Hopper]]

+ La frase más dañina del lenguaje es: "Siempre se ha hecho así".

** [[https://en.wikipedia.org/wiki/Gregory_Chaitin][Gregory Chaitin]]

+ In a way, math isn't the art of answering mathematical questions, it is the
  art of asking the right questions, the questions that give you insight, the
  ones that lead you in interesting directions, the ones that connect with lots
  of other interesting questions -the ones with beautiful answers.
  + En cierto modo, las matemáticas no son el arte de responder preguntas
    matemáticas, es el arte de hacer las preguntas correctas, las preguntas que te
    dan una idea, las que te guían en direcciones interesantes, las que se
    conectan con muchas otras preguntas interesantes, las que tienen hermosas
    respuestas.

+ Mathematical truth is not totally objective. If a mathematical statement is
  false, there will be no proofs, but if it is true, thre will be an endless
  variety of proofs, not just one! Proofs are not impersonal, they express the
  personality of their creator/discoverer just as much as literary efforts
  do. If something important is true, there will be many reasons that it is
  true, many proofs of that fact. Math is the music of reason, and some proofs
  sound like jazz, others sound like a fugue. Which is better, the jazz or the
  fugue?  Neither: it's all a matter of taste...each proof will emphasize
  different aspects of the problem, each proof will lead in a different
  direction. Each one will have different corollaries, different generalizations
  ... Mathematical facts are not isolated, they are woven into a vast spider's
  web of interconnections.

** [[https://en.wikipedia.org/wiki/Henri_Lebesgue][Henri Lebesgue]]

+ The only teaching that a professor can give, in my opinion, is that of
  thinking in front of his students.
  + La única enseñanza que un profesor puede dar, en mi opinión, es la de pensar
    delante de sus alumnos.

** [[https://en.wikipedia.org/wiki/Henri_Poincar%C3%A9][Henri Poincaré]]

+ Duda de los datos hasta que los datos no dejen lugar a dudas.

+ Dudar de todo o creerlo todo son dos opciones igualmente cómodas, pues
  tanto una como otra nos eximen de reflexionar.

+ El sentimiento de la belleza matemática, de la armonía de los números y de
  las formas, de la elegancia geométrica. Es un sentimiento genuinamente
  estético, que todos los matemáticos conocen. Y esto es sensibilidad.

+ El verdadero método para prever el futuro de las matemáticas es estudiar su
  historia y su estado actual.

+ La ciencia son hechos; de la misma manera que las casas están hechas de
  piedras, la ciencia está hecha de hechos; pero un montón de piedras no es
  una casa y una colección de hechos no es necesariamente ciencia.

+ Las matemáticas son el arte de dar el mismo nombre a cosas diferentes.

+ Los descubrimientos matemáticos, pequeños o grandes, nunca se generan
  espontáneamente. Presuponen siempre una sólida base de conocimientos
  preliminares bien madurados por el trabajo consciente y subconsciente.

+ Los matemáticos no estudian objetos, sino relaciones entre objetos. Por lo
  tanto, son libres de reemplazar algunos objetos por otros siempre que las
  relaciones permanezcan sin cambios. El contenido para ellos es irrelevante:
  están interesados ​​únicamente en la forma.

+ Los matemáticos otorgan gran importancia a la elegancia de sus métodos y sus
  resultados. Esto no es puro diletantismo. ¿Qué es lo que realmente nos da la
  sensación de elegancia en una solución, en una demostración? Es la armonía de
  las diversas partes, su simetría, su feliz equilibrio; en una palabra, es todo
  lo que introduce orden, todo lo que da unidad, lo que nos permite ver con
  claridad y comprender a la vez tanto el conjunto como los detalles.

+ Mathematics has a threefold purpose. It must provide an instrument for the
  study of nature. But this is not all: it has a philosophical purpose, and, I
  daresay, an aesthetic purpose.
  + Las matemáticas tienen un triple objetivo. Debe proporcionar un instrumento
    para el estudio de la naturaleza. Pero esto no es todo: tiene un objetivo
    filosófico y, me atrevo a decir, un objetivo estético.

+ Mathematics is the art of giving the same name to different things.
  + Las matemáticas son el arte de dar el mismo nombre a cosas diferentes.

+ Puede ser sorprendente ver la sensibilidad emocional invocada a propósito de
  demostraciones matemáticas que, al parecer, solo pueden interesar al
  intelecto. Esto sería olvidar el sentimiento de belleza matemática, de la
  armonía de números y formas, de elegancia geométrica. Esto es un verdadero
  sentimiento estético que todos los matemáticos reales conocen, y seguramente
  pertenece a la sensibilidad emocional.

+ The mathematician does not study pure mathematics because it is useful; he
  studies it because he delights in it and he delights in it because it is
  beautiful.
  + El matemático no estudia las matemáticas puras porque sean útiles; las
    estudia porque se deleita en ellas y se deleita en ellas porque son hermosas.

+ Todos creen firmemente en ello porque los matemáticos se imaginan que es un
  hecho de observación, y los observadores que es una teoría matemática.

+ Una palabra bien elegida puede economizar no sólo cien palabras, sino cien
  pensamientos.

** [[https://en.wikipedia.org/wiki/Herbert_A._Simon][Herbert A. Simon]]

+ In the computer field, the moment of truth is a running program; all else is
  prophecy.
  + En el campo de la computación, el momento de la verdad es la ejecución de un
    programa; todo lo demás es profecía.

+ ¿Qué consume la información? Consume la atención de sus destinatarios. En
  consecuencia, una riqueza de información crea pobreza de atención, y la
  necesidad de asignar de manera eficiente la atención que entre la
  sobreabundancia de fuentes de información que se pueda consumir es primordial.

** [[https://en.wikipedia.org/wiki/Hermann_Weyl][Hermann Weyl]]

+ Besides language and music, mathematics is one of the primary manifestations
  of the free creative power of the human mind.

+ La investigación matemática eleva la mente humana a una proximidad más
  cercana a lo divino de la que se puede alcanzar a través de cualquier otro
  medio.

+ My work always tried to unite the true with the beautiful; but when I had to
  choose one or the other, I usually chose the beautiful.
  + Mi trabajo siempre trató de unir lo verdadero con lo bello; pero cuando tuve
    que elegir uno u otro, generalmente elegí lo bello.

+ Una prueba matemática moderna no es tan diferente de una máquina moderna:
  simples principios fundamentales están ocultos bajo una masa de detalles
  técnicos.

+ We are not very pleased when we are forced to accept a mathematical truth by
  virtue of a complicated chain of formal conclusions and computations, which we
  traverse blindly, link by link, feeling our way by touch. We want first an
  overview of the aim and of the road; we want to understand the idea of the
  proof, the deeper context.
  + No estamos muy contentos cuando nos vemos obligados a aceptar una verdad
    matemática en virtud de una complicada cadena de conclusiones formales y
    cálculos, que atravesamos a ciegas, eslabón por eslabón, sintiendo nuestro
    camino por el tacto. Queremos primero una visión general del objetivo y del
    camino; queremos entender la idea de la prueba, el contexto más profundo.

** [[https://en.wikipedia.org/wiki/Howard_Eves][Howard Eves]]

+ A good problem should be more than a mere exercise; it should be challenging
  and not too easily solved by the student, and it should require some
  "dreaming" time.

+ There is a distinction between what may be called a problem and what may be
  considered an exercise. The latter serves to drill a student in some
  technique or procedure, and requires little, if any, original thought. In
  contrast to an exercise, a problem, if it is a good one for its level, should
  require thought on the part of the student. It is impossible to overstate the
  importance of problems in mathematics. It is by means of problems that
  mathematics develops and actually lifts itself by its own bootstraps. Every
  new discovery in mathematics results from an attempt to solve some problem.
  + Existe una distinción entre lo que se puede llamar un problema y lo que se
    puede considerar un ejercicio. Este último sirve para entrenar al estudiante
    en alguna técnica o procedimiento, y requiere poco o ningún pensamiento
    original. A diferencia de un ejercicio, un problema, si es apropiado para su
    nivel, debe requerir pensamiento por parte del estudiante. Es imposible
    exagerar la importancia de los problemas en las matemáticas. Es por medio de
    los problemas que las matemáticas se desarrollan y se levantan por sí
    mismas. Cada nuevo descubrimiento en matemáticas es el resultado de un
    intento de resolver algún problema.

+ [[https://es.wikipedia.org/wiki/Ian_Stewart][Ian Stewart]]
+ A menudo, la contribución clave de la intuición es hacernos conscientes de
  los puntos débiles de un problema, los lugares donde puede ser vulnerable a un
  ataque. Una demostración matemática es como una batalla, o si prefiere una
  metáfora menos bélica, una partida de ajedrez. Una vez que se ha identificado
  un punto débil potencial, la comprensión técnica del matemático de la
  maquinaria de las matemáticas puede utilizarse para explotarlo.

+ Criticar a las matemáticas por su abstracción es perder el punto por
  completo. La abstracción es lo que hace que las matemáticas funcionen. Si te
  concentras demasiado en una aplicación demasiado limitada de una idea
  matemática, le robas al matemático sus herramientas más importantes: analogía,
  generalidad, y simplicidad.

+ La intuición matemática es la capacidad de la mente para sentir la forma y la
  estructura, para detectar patrones que no podemos percibir conscientemente. La
  intuición carece de la claridad cristalina de la lógica consciente, pero lo
  compensa al llamar la atención sobre cosas que nunca hubiéramos considerado
  conscientemente.

+ La tendencia del empresario es explotar el mundo natural. La tendencia del
  ingeniero es cambiarlo. La tendencia del científico es tratar de entenderlo, de
  averiguar qué es lo que realmente está sucediendo. La tendencia del matemático
  es estructurar ese proceso de comprensión buscando generalidades que
  atraviesen las subdivisiones obvias.

** [[https://en.wikipedia.org/wiki/Igor_Rivin][Igor Rivin]]

+ La Matemática es una ciencia experimental y la computación es el experimento.

+ Un programa de ordenador es una demostración.

** [[https://en.wikipedia.org/wiki/Isaac_Newton][Isaac Newton]]

+ Lo que sabemos es una gota de agua; lo que ignoramos es el océano.

+ Los hombres construimos demasiados muros y no suficientes puentes.

+ Truth is ever to be found in the simplicity, and not in the multiplicity and
  confusion of things.
  + La verdad siempre se encuentra en la simplicidad, y no en la multiplicidad y
    confusión de las cosas.

** [[https://en.wikipedia.org/wiki/Israel_Nathan_Herstein][Israel Nathan Herstein]]

+ The value of a problem is not so much coming up with the answer as in the
  ideas and attempted ideas it forces on the would be solver.
  + El valor de un problema no es tanto el de encontrar la respuesta como el de
    las ideas e intentos que obliga su resolución.

** [[https://en.wikipedia.org/wiki/Ivars_Peterson][Ivars Peterson]]

+ El misterio es un ingrediente ineludible de las matemáticas. Las matemáticas
  están llenas de preguntas sin respuesta, que superan con creces el número de
  teoremas y resultados conocidos. Está en la naturaleza de las matemáticas el
  plantear más problemas de los que puede resolver. De hecho, la matemática en
  sí misma puede estar construida sobre pequeñas islas de verdad que comprenden
  las piezas de la matemática que pueden ser validadas por pruebas relativamente
  cortas. Todo lo demás es especulación.

** [[https://en.wikipedia.org/wiki/J._Robert_Oppenheimer][J. Robert Oppenheimer]]

+ The hallmark of a science is the avoidance of error.

** [[https://en.wikipedia.org/wiki/Jacques_Hadamard][Jacques Hadamard]]

+ The shortest path between two truths in the real domain passes through the
  complex domain.

** [[https://bit.ly/2vVVv3w][James J Sylvester]]

+ El objetivo constante del matemático es reducir todas sus expresiones a sus
  términos más bajos, reducir cada palabra y frase superflua y condensar el
  Máximo de significado en el Mínimo de lenguaje.

** [[https://en.wikipedia.org/wiki/Jean_Dieudonn%C3%A9][Jean Dieudonné]]

+ No existe un criterio de apreciación que no varíe de una época a otra y de un
  matemático a otro. [...] Estas divergencias en el gusto recuerdan las disputas
  que suscitan las obras de arte, y es un hecho de que los matemáticos a menudo
  discuten entre sí si un teorema es más o menos hermoso. Esto nunca deja de
  sorprender a los profesionales de otras ciencias: para ellos, el único
  criterio es la verdad de una teoría o fórmula.

+ The life of a mathematician is dominated by an insatiable curiosity, a desire
  bordering on passion to solve the problems he is studying.
  + La vida de un matemático está dominada por una insaciable curiosidad, un
    deseo que raya en la pasión por resolver los problemas que estudia.

** [[https://en.wikipedia.org/wiki/Johann_Wolfgang_von_Goethe][Johann Wolfgang von Goethe]]

+ Mathematicians are like Frenchmen: whatever you say to them they translate
  into their own language and forthwith it is something entirely different.

** [[https://bit.ly/3dHi3WH][John Casti]]

+ La verdadera razón de ser de la existencia del matemático es simplemente
  resolver problemas. Entonces, en lo que realmente consisten las matemáticas es
  en problemas y soluciones.

** [[https://en.wikipedia.org/wiki/John_Edensor_Littlewood][John Edensor Littlewood]]

+ Try a hard problem. You may not solve it, but you will prove something else.

** [[https://bit.ly/2WwYbPF][John Stillwell]]

+ Imposibilidades aparentes que son nuevas verdades [...] números irracionales,
  números imaginarios, puntos en el infinito, espacio curvo, ideales y varios
  tipos de infinito. Estas ideas parecen imposibles al principio porque nuestra
  intuición no puede comprenderlas, pero pueden ser capturadas con la ayuda del
  simbolismo matemático, que es una especie de extensión tecnológica de nuestros
  sentidos.

** [[https://bit.ly/2JoTnoc][John Stuart Mill]]

+ Además de acostumbrar al alumno a exigir pruebas completas, y saber cuándo no
  las ha obtenido, los estudios matemáticos son de gran beneficio para su
  educación al habituarlo a la precisión. Es una de las excelencias peculiares
  de la disciplina matemática, que el matemático nunca está satisfecho con à peu
  près. Requiere la verdad exacta.

** [[https://en.wikipedia.org/wiki/John_von_Neumann][John von Neumann]].

+ If people do not believe that mathematics is simple, it is only because they
  do not realize how complicated life is.
  + Si la gente no cree que las matemáticas son simples, es sólo porque no se
    dan cuenta de lo complicada que es la vida.

+ In mathematics, you don't understand things. You just get used to them.

+ La verdad es demasiado complicada para admitir otra cosa que no sean
  aproximaciones.

+ Se espera que un teorema matemático o una teoría matemática no sólo describa
  y clasifique de manera sencilla y elegante numerosos y a priori dispares casos
  especiales. También se espera elegancia en su estructura arquitectónica.

+ We must regard classical mathematics as a combinatorial game played with
  symbols.

** [[https://en.wikipedia.org/wiki/John_Wesley_Young][John Wesley Young]]

+ It is clear that the chief end of mathematical study must be to make the
  students think.

** [[https://en.wikipedia.org/wiki/Joseph-Louis_Lagrange][Joseph Louis Lagrange]]

+ As long as algebra and geometry have been separated, their progress have been
  slow and their uses limited; but when these two sciences have been united,
  they have lent each mutual forces, and have marched together towards
  perfection.

** [[https://en.wikipedia.org/wiki/Joseph_Fourier][Joseph Fourier]]

+ Mathematics compares the most diverse phenomena and discovers the secret
  analogies that unite them.

** [[https://en.wikipedia.org/wiki/Karl_Weierstrass][Karl Weierstrass]]

+ A mathematician who is not also something of a poet will never be a perfect
  mathematician.
  + Un matemático que no sea también algo de poeta nunca será un matemático
    perfecto.

** [[https://en.wikipedia.org/wiki/Kurt_G%C3%B6del][Kurt Gödel]]

+ The development of mathematics towards greater precision has led, as is well
  known, to the formalization of large tracts of it, so that one can prove any
  theorem using nothing but a few mechanical rules.
  + El desarrollo de las matemáticas hacia una mayor precisión ha llevado, como
    es bien sabido, a la formalización de grandes partes de las mismas, de modo
    que se puede probar cualquier teorema usando nada más que unas pocas reglas
    mecánicas.

** [[https://en.wikipedia.org/wiki/L._Peter_Deutsch][L. Peter Deutsch]]

+ To iterate is human, to recurse divine.

** [[https://en.wikipedia.org/wiki/Leo_Tolstoy][Leo Tolstoy]]

+ Some mathematician, I believe, has said that true pleasure lies not in the
  discovery of truth, but in the search for it.
  + Creo que algún matemático ha dicho que el verdadero placer no reside en el
    descubrimiento de la verdad, sino en su búsqueda.

** [[https://en.wikipedia.org/wiki/Leonardo_da_Vinci][Leonardo da Vinci]]

+ Simplicity is the ultimate sophistication.
  + La simplicidad es la última sofisticación.

** [[https://es.wikipedia.org/wiki/Leonhard_Euler][Leonhard Euler]]

+ Algunos hechos se pueden ver más claramente con el ejemplo que con pruebas.

+ Las propiedades de los números conocidos hoy en día han sido descubiertas en
  su mayoría por la observación, y descubiertas mucho antes de que su verdad
  haya sido confirmada por rígidas demostraciones. Hay incluso muchas
  propiedades de los números que conocemos bien, pero que todavía no podemos
  probar; sólo las observaciones nos han llevado a su conocimiento. Por lo
  tanto, vemos que en la teoría de los números, que todavía es muy imperfecta,
  podemos poner nuestras mayores esperanzas en las observaciones.

+ Mejor que de nuestro juicio, debemos fiarnos del cálculo algebraico.

+ Nada ocurre en el mundo cuyo significado no sea el de un máximo o un mínimo.

** [[https://en.wikipedia.org/wiki/Leopold_Kronecker][Leopold Kronecker]]

+ God created the natural number, and all the rest is the work of man
  + Dios creó el número natural, y todo el resto es obra del hombre.

** [[https://es.wikipedia.org/wiki/Linus_Pauling][Linus Pauling]]

+ La mejor forma de tener una buena idea es ... tener un montón de ideas.

** [[https://en.wikipedia.org/wiki/Louis_Pasteur][Louis Pasteur]]

+ Inspiration is the impact of a fact on a well-prepared mind.

** [[https://en.wikipedia.org/wiki/Lucien_Szpiro][Lucien Szpiro]]

+ The difference between mathematicians and physicists is that after physicists
  prove a big result they think it is fantastic but after mathematicians prove
  a big result they think it is trivial.
  + La diferencia entre los matemáticos y los físicos es que después de que los
    físicos prueban un gran resultado piensan que es fantástico, pero después de
    que los matemáticos prueban un gran resultado piensan que es trivial.

** [[https://en.wikipedia.org/wiki/Marcel_Proust][Marcel Proust]]

+ The real voyage of discovery consists not in seeking new landscapes but in
  having new eyes.
  + El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes
    sino en tener nuevos ojos.

** [[https://en.wikipedia.org/wiki/Martin_Fowler_(software_engineer)][Martin Fowler]]

+ Any fool can write code that a computer can understand. Good programmers
  write code that humans can understand. http://bit.ly/MOGKAD
  + Cualquier tonto puede escribir un código que un ordenador puede
    entender. Los buenos programadores escriben código que los humanos pueden
    entender.

** [[https://en.wikipedia.org/wiki/Martin_Gardner][Martin Gardner]]

+ All mathematicians share ... a sense of amazement over the infinite depth and
  the mysterious beauty and usefulness of mathematics.

** [[https://bit.ly/2JntZz3][Marvin Minsky]]

+ La inteligencia artificial es la ciencia de hacer que las máquinas hagan cosas
  que requerirían inteligencia si las hicieran los hombres.

+ Los lenguajes informáticos del futuro estarán más preocupados por los
  objetivos y menos por los procedimientos especificados por el programador.

** [[https://es.wikipedia.org/wiki/Max_Planck][Max Planck]]

+ Una nueva verdad científica no triunfa convenciendo a sus oponentes y
  haciéndoles ver la luz, sino más bien porque sus oponentes finalmente mueren,
  y crece una nueva generación que está familiarizada con ella.

** [[https://es.wikipedia.org/wiki/Michael_Atiyah][Michael Atiyah]]

+ Cualquier buen teorema debe tener varias pruebas, cuanto más mejor. Por dos
  razones: generalmente, las diferentes pruebas tienen diferentes fortalezas y
  debilidades, y se generalizan en diferentes direcciones: no son solo
  repeticiones entre sí.

** [[https://bit.ly/2yhILoO][Morris Kline]]

+ Aunque los conceptos y operaciones matemáticas están formulados para
  representar aspectos del mundo físico, las matemáticas no deben identificarse
  con el mundo físico. Sin embargo, nos dice mucho sobre ese mundo si tenemos
  cuidado de aplicarlo e interpretarlo correctamente.

+ El acto creativo debe poco a la lógica o la razón. En sus relatos de las
  circunstancias bajo las cuales se les ocurrieron grandes ideas, los
  matemáticos a menudo han mencionado que la inspiración no tenía relación con
  el trabajo que estaban realizando. A veces llegaba mientras viajaban, se
  afeitaban o pensaban en otros asuntos. El proceso creativo no puede ser
  convocado a voluntad o incluso engatusado por la ofrenda de sacrificio. De
  hecho, parece ocurrir más fácilmente cuando la mente está relajada y la
  imaginación deambula libremente.

+ La introducción y la aceptación gradual de conceptos que no tienen
  contrapartes inmediatas en el mundo real ciertamente forzó el reconocimiento
  de que las matemáticas son una creación humana, algo arbitraria, en lugar de
  una idealización de las realidades de la naturaleza, derivadas únicamente de
  la naturaleza. Pero acompañar este reconocimiento y, de hecho, impulsar su
  aceptación fue un descubrimiento más profundo: las matemáticas no son un
  cuerpo de verdades sobre la naturaleza.

+ Las matemáticas no representan leyes inherentes al diseño del universo, sino que
  simplemente proporciona esquemas o modelos hechos por el hombre que podemos
  usar para deducir conclusiones sobre nuestro mundo sólo en la medida en que el
  modelo es una buena idealización.

+ The tantalizing and compelling pursuit of mathematical problems offers mental
  absorption, peace of mind amid endless challenges, repose in activity, battle
  without conflict, refuge from the goading urgency of contingent happenings,
  and the sort of beauty changeless mountains present to sense tried by the
  present-day kaleidoscope of events.

+ Una prueba nos dice dónde concentrar nuestras dudas. [...] Una prueba
  elegantemente ejecutada es un poema en todo menos en la forma en que está
  escrito.

** [[https://es.wikipedia.org/wiki/Niels_Bohr][Niels Bohr]]

+ Un experto es una persona que ha cometido todos los errores que se pueden
  cometer en un determinado campo.

** [[https://es.wikipedia.org/wiki/Oliver_Heaviside][Oliver Heaviside]]

+ Las matemáticas son una ciencia experimental, y las definiciones no son lo
  primero, sino lo último.

** [[https://en.wikipedia.org/wiki/Pablo_Picasso][Pablo Picasso]]

+ Computers are useless. They can only give you answers.

** [[https://es.wikipedia.org/wiki/Paul_Cohen][Paul Cohen]]

+ Para el matemático medio que simplemente quiere saber que su trabajo tiene una
  base segura, la opción más atractiva es evitar dificultades por medio del
  programa de Hilbert. Aquí uno considera las matemáticas como un juego formal y
  solo se preocupa por la cuestión de la coherencia.

** [[https://es.wikipedia.org/wiki/Paul_Dirac][Paul Dirac]]

+ Una teoría con belleza matemática es más probable que sea correcta que una fea
  que se ajuste a algunos datos experimentales.

+ Buena parte de mi investigación en física ha consistido en no proponerse
  resolver un problema en particular, sino simplemente examinar las cantidades
  matemáticas de un tipo que los físicos utilizan y tratar de combinarlas de una
  manera interesante.

** [[https://en.wikipedia.org/wiki/Paul_Erd%C5%91s][Paul Erdős]]

+ Every human activity, good or bad, except mathematics, must come to an end.

+ Who can does; who cannot do, teaches; who cannot teach, teaches teachers.

+ Why are numbers beautiful? It's like asking why is Beethoven's Ninth Symphony
  beautiful. If you don't see why, someone can't tell you. I know numbers are
  beautiful. If they aren't beautiful, nothing is.
  + ¿Por qué son hermosos los números? Es como preguntar por qué es bella la
    Novena Sinfonía de Beethoven. Si no ves por qué, alguien no puede
    decírtelo. Yo sé que los números son hermosos. Si no son hermosos, nada lo
    es.

** [[https://en.wikipedia.org/wiki/Paul_Halmos][Paul Halmos]]

+ A good stack of examples, as large as possible, is indispensable for a
  thorough understanding of any concept, and when I want to learn something
  new, I make it my first job to build one.
  + Una buena pila de ejemplos, tan grande como sea posible, es indispensable
    para una comprensión profunda de cualquier concepto, y cuando quiero
    aprender algo nuevo, mi primer trabajo es construir uno.

+ Es el deber de todos los profesores, y de los profesores de matemáticas en
  particular, exponer a sus alumnos a problemas mucho más que a hechos.

+ La alegría de aprender repentinamente un secreto anterior y la alegría de
  descubrir repentinamente una verdad desconocida hasta ahora son las mismas
  para mí. Ambas tienen el destello de la iluminación, la visión casi
  increíblemente mejorada, y el éxtasis y la euforia de la tensión liberada.

+ Mathematics is not a deductive science – that's a cliché. When you try to
  prove a theorem, you don't just list the hypotheses, and then start to
  reason. What you do is trial and error, experimentation, guesswork.
  + Las matemáticas no son una ciencia deductiva, eso es un cliché. Cuando
    tratas de probar un teorema, no te limitas a enumerar las hipótesis y luego
    empiezas a razonar. Lo que haces es prueba y error, experimentación,
    conjetura.

+ No sólo lo leas; ¡lucha! Haz tus propias preguntas, busca tus propios
  ejemplos, descubre tus propias pruebas.

+ Un profesor que no siempre está pensando en resolver problemas -de los que no
  conoce la respuesta- simplemente no está psicológicamente preparado para
  enseñarles a sus alumnos a resolver problemas.

** [[https://en.wikipedia.org/wiki/Paul_Hudak][Paul Hudak]]

+ Programación, en sentido amplio, es resolución de problemas.

** [[https://en.wikipedia.org/wiki/A_Mathematician%27s_Lament][Paul Lockhart]]

+ Hacer matemáticas siempre debe significar encontrar patrones y crear
  explicaciones hermosas y significativas.

+ La agudeza mental de cualquier tipo proviene de resolver problemas por ti
  mismo, no de que te digan cómo resolverlos.

+ La enseñanza no se limita a la información. Se trata de tener una relación
  intelectual honesta con tus alumnos.

+ Las matemáticas son el arte de la explicación. Si les niega a los estudiantes
  la oportunidad de participar en esta actividad, de plantear sus propios
  problemas, de hacer sus propias conjeturas y descubrimientos, de equivocarse,
  de frustrarse creativamente, de inspirarse y de preparar sus propias
  explicaciones y pruebas, les niega la matemática misma.

+ Si hay algo así como un principio estético unificador en matemáticas, es
  este: lo simple es hermoso. Los matemáticos disfrutan pensando en las cosas
  más simples posibles, y las más simples son fantásticas.

+ Un buen problema es algo que no sabes cómo resolver. Eso es lo que lo hace un
  buen rompecabezas y una buena oportunidad.

** [[https://en.wikipedia.org/wiki/Pierre_Boutroux][Pierre Boutroux]]

+ Logic is invincible, because in order to combat logic it is necessary to use
  logic.
  + La lógica es invencible, porque para combatir la lógica es necesario usar la
    lógica.

** [[https://en.wikipedia.org/wiki/Pierre-Simon_Laplace][Pierre-Simon Laplace]]

+ What we know is not much. What we do not know is immense.

** [[https://en.wikipedia.org/wiki/Ralph_P._Boas_Jr.][Ralph P. Boas Jr.]]

+ Only professional mathematicians learn anything from proofs. Other people
  learn from explanations.

** [[https://en.wikipedia.org/wiki/Raymond_S._Nickerson][Raymond S. Nickerson]]

+ Además de considerar las matemáticas como el estudio de patrones, las
  matemáticas pueden ser vistas, pragmáticamente, como una vasta colección de
  problemas de ciertos tipos y de enfoques que han demostrado ser efectivos para
  resolverlos.

+ Sin negar la utilidad de la distinción entre intuición y prueba, creo que se
  puede hacer con demasiada agudeza; la intuición desempeña un papel esencial en
  la elaboración y evaluación de las pruebas y a veces se modifica como
  consecuencia de estos procesos. En este sentido, la distinción es como la del
  pensamiento creativo y el pensamiento crítico; aunque esta distinción también
  es útil, no es posible tenerla en un sentido muy satisfactorio sin el otro.

** [[https://en.wikipedia.org/wiki/Ren%C3%A9_Descartes][René Descartes]]

+ Each problem that I solved became a rule which served afterwards to solve
  other problems.

** [[https://es.wikipedia.org/wiki/Richard_Courant][Richard Courant]] y [[https://en.wikipedia.org/wiki/Herbert_Robbins][Herbert Robbins]]

+ El hecho de que la prueba de un teorema consista en la aplicación de ciertas
  reglas simples de lógica no elimina el elemento creativo en las matemáticas,
  que radica en la elección de las posibilidades a examinar.

+ Mathematics as an expression of the human mind reflects the active will, the
  contemplative reason, and the desire for aesthetic perfection. Its basic
  elements are logic and intuition, analysis and construction, generality and
  individuality.
  + Las matemáticas como expresión de la mente humana reflejan la voluntad
    activa, la razón contemplativa y el deseo de perfección estética. Sus
    elementos básicos son la lógica y la intuición, el análisis y la
    construcción, la generalidad y la individualidad.

** [[https://en.wikipedia.org/wiki/Richard_Dedekind][Richard Dedekind]]

+ I see it, but I don't believe it. [On Cantor's proof that the points in the
  unit interval were in one-to-one correspondence with points in the unit
  square.]

** [[https://en.wikipedia.org/wiki/Richard_Feynman][Richard Feynman]]

+ La mejor enseñanza sólo puede hacerse cuando hay una relación individual
  directa entre un estudiante y un buen profesor: una situación en la que el
  estudiante discute las ideas, piensa sobre las cosas y habla sobre las cosas. Es
  imposible aprender mucho asistiendo simplemente a una lección, o incluso
  haciendo simplemente los problemas que se proponen.

+ Necesitamos enseñar a que la duda no sea temida, sino bienvenida y
  debatida. No hay problema en decir: 'No lo sé'.

+ Para aquellos que no conocen las matemáticas, es difícil sentir la belleza, la
  profunda belleza de la naturaleza... Si quieres aprender sobre la naturaleza,
  apreciar la naturaleza, es necesario aprender el lenguaje en el que habla.

+ Una medida de nuestro entendimiento es el número de formas independientes de
  llegar al mismo resultado.

+ We decided that 'trivial' means 'proved'. So we joked with the mathematicians:
  We have a new theorem - that mathematicians can prove only trivial theorems,
  because every theorem that's proved is trivial.

** [[https://en.wikipedia.org/wiki/Richard_Hamming][Richard Hamming]]

+ If you don’t work on important problems, it’s not likely that you’ll do
  important work.

+ The purpose of computing is insight, not numbers.
  + El propósito de la computación es la comprensión, no los números.

** [[https://en.wikipedia.org/wiki/Robert_Harper_(computer_scientist)][Robert Harper]]

+ Programming is an explanatory activity.

** [[https://en.wikipedia.org/wiki/R%C3%B3zsa_P%C3%A9ter][Rózsa Péter]]

+ I love mathematics... principally because it is beautiful, because man has
  breathed his spirit of play into it, and because it has given him his
  greatest game - the encompassing of the infinite.

+ I love mathematics not only because it is applicable to technology but also
  because it is beautiful.

** [[https://en.wikipedia.org/wiki/Sim%C3%A9on_Denis_Poisson][Siméon Denis Poisson]]

+ Life is good for only two things, discovering mathematics and teaching
  mathematics.
  + La vida merece la pena sólo por dos cosas: por descubrir las matemáticas y
    por enseñarlas.

** [[https://en.wikipedia.org/wiki/Stanislaw_Ulam][Stanislaw Ulam]]

+ El lado estético de las matemáticas ha sido de una importancia abrumadora a
  lo largo de su desarrollo. Lo que importa no es si un teorema es útil, sino lo
  elegante que es.

+ Good mathematicians see analogies between theorems and theories. The very best
  ones see analogies between analogies.
  + Los buenos matemáticos ven analogías entre los teoremas y las teorías. Los
    mejores ven analogías entre analogías.

+ In many cases, mathematics is an escape from reality. The mathematician finds
  his own monastic niche and happiness in pursuits that are disconnected from
  external affairs. Some practice it as if using a drug. Chess sometimes plays
  a similar role. In their unhappiness over the events of this world, some
  immerse themselves in a kind of self-sufficiency in mathematics. (Some have
  engaged in it for this reason alone.)
  + En muchos casos, las matemáticas son un escape de la realidad. El matemático
    encuentra su propio nicho monástico y la felicidad en actividades que están
    desconectadas de los asuntos externos. Algunos lo practican como si usaran
    una droga. El ajedrez a veces juega un papel similar. En su infelicidad por
    los acontecimientos de este mundo, algunos se sumergen en una especie de
    autosuficiencia en matemáticas. (Algunos se han dedicado a ello por esta
    sola razón).

+ Los matemáticos saben mucho sobre muy poco y los físicos muy poco sobre
  mucho.

+ ¿Qué es exactamente la matemática? Muchos lo han intentado, pero nadie ha
  logrado definir las matemáticas; siempre es otra cosa.

** [[https://en.wikipedia.org/wiki/Stefan_Banach][Stefan Banach]]

+ A mathematician is a person who can find analogies between theorems; a better
  mathematician is one who can see analogies between proofs and the best
  mathematician can notice analogies between theories. One can imagine that the
  ultimate mathematician is one who can see analogies between analogies.
  + Un matemático es una persona que puede encontrar analogías entre teoremas;
    un mejor matemático es uno que puede ver analogías entre pruebas y el mejor
    matemático puede notar analogías entre teorías. Uno puede imaginar que el
    mejor matemático es aquel que puede ver analogías entre analogías.

** [[https://es.wikipedia.org/wiki/Steve_Jobs][Steve Jobs]]

+ Learning to program teaches you how to think. Computer science is a liberal
  art.

** [[https://en.wikipedia.org/wiki/Sydney_J._Harris][Sydney J. Harris]]

+ The real danger is not that computers will begin to think like men, but that
  men will begin to think like computers.
  + El verdadero peligro no es que los ordenadores empiecen a pensar como los
    hombres, sino que los hombres empiecen a pensar como los ordenadores.

** [[https://en.wikipedia.org/wiki/Tony_Hoare][Tony Hoare]]

+ ¿Cuál es el núcleo central de la ciencia de la computación? ¿Qué es lo que lo
  diferencia de los otros temas con los que se relaciona? ¿Qué es lo que el hilo
  de unión que reúne estas ramas dispares en una sola disciplina? Mi respuesta a
  estas preguntas es simple - es el arte de programar un ordenador. Es el arte
  de diseñar métodos eficientes y elegantes para conseguir que un ordenador
  resuelva problemas, teóricos o prácticos, pequeños o grandes, simples o
  complejos. Es el arte de traducir estos diseños programas correctos y
  eficientes.

+ Hay dos maneras de diseñar un software. Una forma es hacerlo tan simple que
  obviamente no haya deficiencias. Y la otra forma es hacerlo tan complicado que
  no haya deficiencias obvias.

+ En el desarrollo de la comprensión de los fenómenos complejos, la herramienta
  más poderosa de que dispone el intelecto humano es la abstracción. La
  abstracción surge del reconocimiento de las similitudes entre ciertos objetos,
  situaciones o procesos en el mundo real y de la decisión de concentrarse en
  estas similitudes e ignorar, por el momento, sus diferencias.

** [[https://bit.ly/2Y60TMJ][Wernher von Braun]]

+ Investigación es lo que hago cuando no sé lo que estoy haciendo.

** [[https://bit.ly/2UJtdSf][William S Jevons]]

+ A medida que la ciencia progresa, su poder de previsión aumenta rápidamente,
  hasta que el matemático en su biblioteca adquiere el poder de anticipar la
  naturaleza y predecir lo que sucederá en circunstancias que el ojo del hombre
  nunca ha examinado.

** [[https://es.wikipedia.org/wiki/William_Thurston][William Thurston]]

+ Las matemáticas son increíblemente comprimibles: puede que tenga que luchar
  mucho tiempo, paso a paso, para trabajar en algún proceso o idea desde varios
  enfoques. Pero una vez que realmente lo entiendes y tienes la perspectiva
  mental para verlo como un todo, hay una tremenda compresión mental. Puedes
  archivarlo, recuperarlo rápida y completamente cuando lo necesites, y usarlo
  como un solo paso en algún otro proceso mental. La idea que acompaña a esta
  compresión es una de las verdaderas alegrías de las matemáticas.

+ Las matemáticas no tratan de números, ecuaciones, cálculos o algoritmos: se
  trata de entender.

** [[https://en.wikipedia.org/wiki/Yuri_Manin][Yuri Manin]]

+ Most likely, logic is capable of justifying mathematics to no greater extent
  than biology is capable of justifying life.


* Publicados en Twitter

+ "Let us change our traditional attitude to the construction of programs:
  Instead of imagining that our main task is to instruct a computer what to do,
  let us concentrate rather on explaining to human beings what we want a
  computer to do." ~ Donald E. Knuth #Quote #CompSci

+ "Computer Science as the continuation of Logic by other means." ~ Georg
  Gottlob #Quote #CompSci #Logic

* Fuentes

+ [[https://www.defprogramming.com/authors/][defprogramming]]
+ [[https://en.wikiquote.org/wiki/Category:Computer_scientists][Category:Computer_scientists]].
